### ISSUE TITLE
Deadlock conflict local global planner

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_robocup#102]

**Comment by jlunenburg** [comment]
We don't use the NavigateState anymore to continuously update a global plan (e.g., when following someone) anymore, do we? 

If so, I guess it's fair to assume that it doesn't make any sense to ask for a plan multiple times starting from the same position. @reinzor do you agree?

**Comment by reinzor** [comment]
I agree, however, it can be that the plan becomes free again after a
specific amount of time. This is not necessarily the same plan so
requesting plans still makes sense.

-Rein

**Comment by reinzor** [comment]
Was this issue resolved?
