### ISSUE TITLE
Nodes in scripts or nodes folder?

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#1089]
As @Timple mentioned in https://github.com/tue-robotics/node_alive/commit/6b015b71d4a8e72a68fca4fbbee725294ac7fc65#commitcomment-47542367, nodes should actually be placed in a nodes folder instead of scripts.

Do we want to apply to this convention or keep everything in scripts? In we do want to apply, force a refactor or converge slowly?

**Comment by ar13pit** [comment]
Actually neither. In setuptools the convention is to have it generated automatically by referring to a function in the library. So until then I think we can stick on with scripts and should slowly proceed to using setuptools

**Comment by Timple** [comment]
> In setuptools the convention is to have it generated automatically

Cool! Do you have a reference for this?

**Comment by ar13pit** [comment]
> > In setuptools the convention is to have it generated automatically
> 
> Cool! Do you have a reference for this?

Yes its called entry points, through console_scripts (https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html)

**Comment by MatthijsBurgh** [comment]
Conclusion:
>In setuptools the convention is to have it generated automatically by referring to a function in the library. So until then I think we can stick on with scripts and should slowly proceed to using setuptools
