### ISSUE TITLE
Model creator

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_robocup#112]
@jlunenburg @svddries

**Comment by jlunenburg** [comment]
Areas:
  - name: on_top_of
  - name: in_front_of
  - name: near
 In geval van een kast:
- shelves

Let op flow-styles (leesbaarheid)

Dingen die je modelleert als een blok (b.v. de koelkast)

Script staat op: ed_object_models/scripts/create-model.py

Bekijken van een object: rosrun ed ed_view_model --model reo2016

**Comment by reinzor** [comment]
Weet niet of dit hier mee te maken heeft maar dinnertable in front of klopt niet meer in robotics testlabs

**Comment by LoyVanBeek** [comment]
Zijn de assen van de modellen niet gedraaid? Bijv dat X altijd naar de voorkant van een object wijst?
