### ISSUE TITLE
Inconsistent API of detect_faces

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#1264]
In [perception.py](https://github.com/tue-robotics/tue_robocup/blob/master/robot_skills/src/robot_skills/perception.py), `detect_faces` either returns a `list[image_recognition_msgs/Recognition]` or a `tuple[list[image_recognition_msgs/Recognition], stamp`, depending on the input. This is error prone. 

Whenever updating this, all uses in this repo as well as other packages/repos (`action_server`) need to be checked.

**Comment by MatthijsBurgh** [comment]
I think this one is very easy. Just always return the stamp. Than the user can determine to use it or not

**Comment by PetervDooren** [comment]
#1265
