### ISSUE TITLE
Prep for BEP students Q1 2023/2024

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue_robocup#1324]
In Q1 three new students will start. We should set up the modules they will be working on so they can get started right away without messing around with our codebase.
We need to:
- Find the place for their functionality in our codebase.
- Write the receivers for the sensordata they will be working with.
- Write the output they need to provide in the end. 
- Describe the procedure they will need to take to test their module

The three assignments are:
**Unknown table placing 3.0**
Place an object on an unmodeled surface
- [x] visualize the emptyspot designator from Max.
- [x] publish a pose message.
-  Add something to place.py to call the emptyspotfinder service. ( algorithm is still too unstable to use for placing. )
- [x] clean up the code of the emptyspotfinder.

Visual servoing:
- [x] make a smach state with a robot object.
- [ ] get images from the hand camera.
- [x] allow arm end effector goals to be sent.
- [x] Allow control of the base.
- [ ] print an aruco marker for the basket handle.

People tracking:
- [x] make an ed plugin? or smach state? for people tracking. Its an executable now, its own package in people_recognition.
- [x] get peopledetections 2D / openpose measurements.
- [ ] visualise pose of person with respect to robot.
- [ ] control head
- [ ] control base

**Comment by MatthijsBurgh** [comment]
You mean people 3D instead of 2D?

**Comment by PetervDooren** [comment]
Nope, 2D. The robot only needs to know the direction of the person. Distance is optional. I think it should be more robust with 2D as 3D sometimes gets incorrect associations. But this is just a hypothesis.

**Comment by MatthijsBurgh** [comment]
In Bordeaux we experienced the depth measurements of the people detection is off. The resulting position of the detected persons is closer than it should be.

The question is whether the error is in the camera data, any of the camera model logic or the logic in people_detection
