### ISSUE TITLE
Inspect object: look too high

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#133]

**Comment by MatthijsBurgh** [comment]
As suggested on whatsapp. This was maybe caused by the wrong orientation of the object. After adapting models to new standard. Placing the infrontof area behind the object in the wall. Object is now in the correct orientation. Needs to be checked.

**Comment by MatthijsBurgh** [comment]
Last week, during the demo, Amigo did not have any problem with looking on top of the cabinet and dinnertable.
