### ISSUE TITLE
Laptop bracket on SERGIO

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#142]
For the restaurant and follow-and-guide challenges a laptop bracket on the back of SERGIO is desired

**Comment by hvrooy** [comment]
Which laptop (size, weight)? 
Will the laptop be opened (and operated) or closed?
Is it a permanent bracket, or must it be (easily) removeable?
Is it needed on the enclosure (torso backplane) later too? (this requires a different or new design)
Is it possible to use a tablet too, or instead?

**Comment by MatthijsBurgh** [comment]
15 inch HP laptop
The laptop Will always be open during  challanges. Does not need to be permanent, Just for Leipzig at the moment.
It has to be a Linux machine with Ethernet port. In some challenges, SERGIO will drive away from the arena with a possible chance of losing Wi-Fi connection. Therefore the laptop, which runs the ssh session, need to have a wired connection.

**Comment by MatthijsBurgh** [comment]
Done
