### ISSUE TITLE
[RIPS] Just after opening door: ED entity initial_pose does not exist

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_robocup#15]
[INFO] [WallTime: 1422025023.032205] State machine transitioning 'INITIALIZE':'initialized'-->'INSTRUCT_WAIT_FOR_DOOR'
[INFO] [WallTime: 1422025023.033290] 'Hi there, I will now wait until the door is opened'
[INFO] [WallTime: 1422025023.038794] State machine transitioning 'INSTRUCT_WAIT_FOR_DOOR':'spoken'-->'ASSESS_DOOR'
[INFO] [WallTime: 1422025023.140899] State machine transitioning 'ASSESS_DOOR':'laser_read'-->'WAIT_FOR_DOOR'
[INFO] [WallTime: 1422025023.342844] State machine transitioning 'WAIT_FOR_DOOR':'query_true'-->'DOOR_OPEN'
[INFO] [WallTime: 1422025023.344028] 'Door is open!'
[INFO] [WallTime: 1422025023.350039] State machine transitioning 'DOOR_OPEN':'spoken'-->'INIT_POSE'
[ERROR] [WallTime: 1422025023.361855] SetInitialPose: ED entity 'initial_pose' does not exist.
[ERROR] [WallTime: 1422025023.363716] InvalidUserCodeError: Could not execute state 'INIT_POSE' of type '<robot_smach_states.utility_states.SetInitialPose object at 0x43d8950>': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/hydro/system/src/robot_smach_states/src/robot_smach_states/utility_states.py", line 88, in execute
    x,y,phi = self.location_2d(self.initial_position)
ValueError: need more than 0 values to unpack

[ERROR] [WallTime: 1422025023.364765] State 'START_CHALLENGE_ROBUST' failed to execute.
[ERROR] [WallTime: 1422025023.366403] Robot exited with smach.exceptions.InvalidUserCodeError,<smach.exceptions.InvalidUserCodeError instance at 0x7f30d0018908>,<traceback object at 0x7f30d0008560>

**Comment by Rayman** [comment]
fixed by tue-robotics/ed@d595e274769c4bda88f221685d0ece6836462a02
