### ISSUE TITLE
Use Entity class instead of plain EntityInfo-message

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#151]
Setup and use a more general Entity-class. Currently, we use EntityInfo a lot, but much code is duplicated when operating on that data.
This can be reduced when abstracting over EntityInfo with the Entity-class.

class Entity, with attributes:
- pose: KDL.Frame
- type & super_types 
- convex_hull
- volumes
Methods:
- is_a, to check the types and super-types
- distance_to-{2,3}d

**Comment by LoyVanBeek** [comment]
This directly makes the switch to KDL datatypes. Maybe we should wait with that and first give Entity a geometry_msgs.Pose first and then convert everything to KDL.Frame. 

Makes the switch easier to grok and test.

**Comment by LoyVanBeek** [comment]
Also, a method to convert its pose to a geometry_msgs.Pose wrt. a given frame (defaulting to /map) would be handy in a lot of places as well.

**Comment by Rayman** [comment]
For conversion, see all the methods here:
https://github.com/ros/geometry2/blob/indigo-devel/tf2_kdl/src/tf2_kdl/tf2_kdl.py

Looks quite nice, they even have tf2_ros.Stamped versions of KDL vectors.
