### ISSUE TITLE
Service /amigo/ed/fit_entity_in_image not running for challenge_manipulation

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#153]
And when is does run, with `amiddle-manipulation-gmapping robotics_testlabs`, it doesn't work and fails everything

> [INFO] [WallTime: 1484084375.165510] State machine transitioning 'RESET_ED_SLAM':'done'-->'FIT_ENTITY'
> [INFO] [WallTime: 1484084376.967997] Trying to fit...
> [ERROR] [WallTime: 1484084378.010455] Fit entity: error_msg: Could not capture image
> [INFO] [WallTime: 1484084378.010756] State machine transitioning 'FIT_ENTITY':'failed'-->'SAY_FITTING_FAILED'

**Comment by reinzor** [comment]
People are responsible for their own world model instance at a challenge
