### ISSUE TITLE
Make all robot parts inherit from a common base class

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#158]
This class, RobotPart, has the following methods:
- close() --> with cancels all active goals.
- reset(timeout=X) which brings it to a known state
- cancel_goal() which cancels the current goals (called by close())

There might be a case for a MovableBodyPart-subclass, which also defines:
- send_goal(..., timeout=X) the arguments of which are specific to the body part
- wait_for_motion_done()

**Comment by MatthijsBurgh** [comment]
Is this solved by 221621708398a0204134b346dc85824104f126b7?

**Comment by LoyVanBeek** [comment]
By https://github.com/tue-robotics/tue_robocup/pull/184 actually
