### ISSUE TITLE
r5cob: Could not play /tmp/2017-02-28-22-07-43.wav

### ISSUE THREAD

**Issue by Timple** [tue-robotics/tue_robocup#174]
[ERROR] [1488316063.372908]: Could not play /tmp/2017-02-28-22-07-43.wav: return code: 512

Happens on amigo

**Comment by MatthijsBurgh** [comment]
Is this still a issue?

**Comment by Timple** [comment]
Yes. Today I had: could not play /tmp/.wav

Op 14 mrt. 2017 9:30 p.m. schreef "Matthijs van der Burgh" <
notifications@github.com>:

**Comment by reinzor** [comment]
This is a bug in text to speech

**Comment by reinzor** [comment]
Resolved
