### ISSUE TITLE
Laser filter parameters due to new laser drivers

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_robocup#176]
![image](https://cloud.githubusercontent.com/assets/4176023/23679657/d989dcaa-0388-11e7-8632-e4e927ec65d8.png)

**Comment by reinzor** [comment]
https://github.com/tue-robotics/amigo_bringup/pull/28 Closes this issue

**Comment by reinzor** [comment]
Not fixed!

**Comment by MatthijsBurgh** [comment]
fixed by tue-robotics/amigo_bringup@769f625ff09529c361f3ecade65c351f9b1621a4
