### ISSUE TITLE
Something with right_arm, output of amigo-start

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#179]
tue_robocup and action_server on LoyVanBeek-patch-1. Unknown which node.
In simulator, AMIGO grasp something  drives back, keeps arm stretched. Then retracts but than stretches again.

[ERROR] [1489143460.400993823]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143465.511066301]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143470.621891784]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143475.763468481]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143480.901972693]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143486.019970749]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143491.162145317]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143496.318188951]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143501.478219334]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143506.623142394]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143511.748413301]: right_arm[default]: Unable to sample any valid states for goal tree
[ERROR] [1489143516.877308706]: right_arm[default]: Unable to sample any valid states for goal tree

**Comment by reinzor** [comment]
This is move it
