### ISSUE TITLE
Inspect should have optional area as input

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#180]

**Comment by LoyVanBeek** [comment]
No, i think it should be the other way around: when you query the worldmodel, select only the objects within some volume, after they are already added. 

I don't think the ED segmented can only work in a specific volume and I don't think is should

**Comment by MatthijsBurgh** [comment]
The area is already used as input. I don't know what happens under the hood, but an area is related to a surface.

**Comment by LoyVanBeek** [comment]
Entities have volumes (which are named area's in the Ed.EntityInfo msg).
