### ISSUE TITLE
EmptySpotDesignator does not work

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#185]
Orientations are completely wrong

**Comment by LoyVanBeek** [comment]
Problem is likely to be because of the refactoring :-/

**Comment by jlunenburg** [comment]
if __name__ == "__main__":
    # import doctest
    # doctest.testmod()

    rospy.init_node("testdesignator")
    from robot_skills.amigo import Amigo
    robot = Amigo()
    furniture_designator = EdEntityDesignator(robot, id="dinner_table")
    esd = EmptySpotDesignator(robot=robot, place_location_designator=furniture_designator, name = None,
                              area = "on_top_f")
    esd.resolve()

**Comment by LoyVanBeek** [comment]
Fixed in https://github.com/tue-robotics/tue_robocup/pull/192
