### ISSUE TITLE
Cleanup kdl_conversions

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#193]
- [ ] CamelCased function names
- [ ] Two functions that create a FrameStamped from x, y, z, roll, pitch, yaw, frame_id

**Comment by LoyVanBeek** [comment]
As far as I can see, there is only one thing that creates

-  a Frame from x, y, z, roll, pitch, yaw (https://github.com/tue-robotics/tue_robocup/blob/master/robot_skills/src/robot_skills/util/kdl_conversions.py#L203)
-  and a FrameStamped from x, y, z, roll, pitch, yaw, frame_id (https://github.com/tue-robotics/tue_robocup/blob/master/robot_skills/src/robot_skills/util/kdl_conversions.py#L225) 

Or do you means something else

**Comment by Rayman** [comment]
The CamelCased function names is still an issue
