### ISSUE TITLE
TrajectoryActionLib en tue::manipulation::ReferenceGenerator

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#199]
Somewhere in those two, stuff is going wrong.
How to test: send frequent goals to torso in amigo-console. Can even be the same goal

**Comment by reinzor** [comment]
Can be closed if the following PR's are merged:

https://github.com/tue-robotics/tue_manipulation/pull/13
https://github.com/tue-robotics/rtt_control_components/pull/40
