### ISSUE TITLE
GPSR Speech generator

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#20]
I saw the README with possibilities. Maybe we should use a random generator as well. Even if this is simple, it prevents us from asking AMIGO the same questions over and over again. Furthermore, even if it sometimes spits out something impossible, we can request the next.

**Comment by egeerts** [comment]
@reinzor created yesterday the speech generator. Included in README of gpsr. Only there were some problems with the spec for the recognizer. With dummy it works, but not on the robot. Needs more investigation.
