### ISSUE TITLE
ed segment service call is crashing

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_robocup#203]
https://github.com/tue-robotics/ed_sensor_integration/issues/4

**Comment by MatthijsBurgh** [comment]
https://github.com/tue-robotics/ed_sensor_integration/issues/4 is closed, so what is status of this one?

**Comment by MatthijsBurgh** [comment]
Fixed?

**Comment by reinzor** [comment]
Yes 

-Rein
