### ISSUE TITLE
Discuss the way how everybody is sending goals to the hardware

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_robocup#204]
The following PR's will fix the infinite while loop that was present in the trajectory actionlib interface:

https://github.com/tue-robotics/tue_manipulation/pull/13
https://github.com/tue-robotics/rtt_control_components/pull/40

However, if the reference generator fails, this is reported back to the caller so the caller cannot assume that all trajectories will be executing properly. This assumption is done in a lot off challenges/states etc which have to be revised. We have to discuss how we are going to send goals to the hardware since sending multiple goals in different ways without checking if the preceding goal is done, effect the motion realization now.

**Comment by LoyVanBeek** [comment]
If this is done though action clients, a way to check the status should be built-in and the robot_skills (optionally) check for this.
