### ISSUE TITLE
Record RoboCup

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#212]
When starting a challenge, I get the following error: [ERROR] [1491640854.401790]: Could not find record_robocup.launch in bringup package of robot amigo

**Comment by MatthijsBurgh** [comment]
https://github.com/tue-robotics/amigo_bringup/blob/master/launch/util/record_robocup.backup
Dus waarschijnlijk gewoon ff verplaatsen

**Comment by MatthijsBurgh** [comment]
Is this one fixed?

**Comment by jlunenburg** [comment]
Should check if this is installed by default

**Comment by MatthijsBurgh** [comment]
Missing dependencies fixed of audio_capture by e5e9a28d5821265313f85772f70b629c1422dca2
