### ISSUE TITLE
Threshold object recognition result

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#220]

**Comment by MatthijsBurgh** [comment]
Is tue-robotics/ed_perception@4b4ff8de3304f8e88680d5dfdf4d5f1a5b1ec3ac enough for this issue to be closed? Or is this still open for implementation on the other side?

**Comment by jlunenburg** [comment]
Is now 0.3 in storing groceries, seems sufficiently reliable
