### ISSUE TITLE
Bug if question not answered

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#225]
Crashed during runthrough

**Comment by jlunenburg** [comment]
Is probably adding skybiometry to launch file

**Comment by jlunenburg** [comment]
Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/challenge_spr/src/challenge_spr.py", line 107, in <module>
    startup(ChallengeSpeechPersonRecognition, challenge_name="challenge_spr")
  File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/util/startup.py", line 91, in startup
    outcome = executioner.execute()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 266, in _update_once
    self._current_state.get_registered_outcomes()))
smach.exceptions.InvalidTransitionError: Attempted to return outcome 'not_answered' from state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f38bfcb0690>' which only has registered outcomes: ('answered',)

**Comment by jlunenburg** [comment]
amigo@amigo2 $ roslaunch challenge_spr.launch 
... logging to /home/amigo/.ros/log/1e26d58e-1c5c-11e7-a82e-00031d0a0d6c/roslaunch-amigo2-4349.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://amigo2:34800/

SUMMARY
========

PARAMETERS
 * /amigo/face_recognition/align_path: ~/openface/models...
 * /amigo/face_recognition/net_path: ~/openface/models...
 * /amigo/face_recognition/save_images: True
 * /amigo/face_recognition/save_images_folder: ~/MEGA/data/robot...
 * /amigo/global_planner/base_global_planner: base_navigation::...
 * /amigo/global_planner/global_costmap/always_send_full_costmap: True
 * /amigo/global_planner/global_costmap/configuration_space/dilation_cell_value: 253
 * /amigo/global_planner/global_costmap/configuration_space/dilation_radius: 0.37
 * /amigo/global_planner/global_costmap/configuration_space/inflation_radius: 0.6
 * /amigo/global_planner/global_costmap/configuration_space/target_cell_value: 254
 * /amigo/global_planner/global_costmap/configuration_space/use_footprint: False
 * /amigo/global_planner/global_costmap/ed_occupancy_grid/map_topic: /amigo/ed/navigat...
 * /amigo/global_planner/global_costmap/ed_occupancy_grid/track_unknown_space: False
 * /amigo/global_planner/global_costmap/global_frame: /map
 * /amigo/global_planner/global_costmap/plugins: [{'type': 'costma...
 * /amigo/global_planner/global_costmap/publish_frequency: 1.0
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/clearing: False
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/data_type: LaserScan
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/inf_is_valid: True
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/marking: True
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/observation_persistence: 0.0
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/obstacle_range: 10.0
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/ray_trace_range: 10.0
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/sensor_frame: /amigo/base_laser
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/topic: /amigo/base_laser...
 * /amigo/global_planner/global_costmap/recent_obstacles/observation_sources: base_laser torso_...
 * /amigo/global_planner/global_costmap/recent_obstacles/occupied_to_default_time: 2.0
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/data_type: PointCloud2
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/expected_update_rate: 1.0
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/max_obstacle_height: 0.5
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/min_obstacle_height: 0.0
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/observation_persistence: 0.0
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/obstacle_range: 10
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/sensor_frame: /amigo/top_kinect...
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/topic: /amigo/ed/navigat...
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/clearing: False
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/data_type: LaserScan
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/inf_is_valid: True
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/marking: True
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/observation_persistence: 0.0
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/obstacle_range: 10.0
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/ray_trace_range: 10.0
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/sensor_frame: /amigo/torso_laser
 * /amigo/global_planner/global_costmap/recent_obstacles/torso_laser/topic: /amigo/torso_lase...
 * /amigo/global_planner/global_costmap/resolution: 0.05
 * /amigo/global_planner/global_costmap/robot_base_frame: /amigo/base_link
 * /amigo/global_planner/global_costmap/rolling_window: False
 * /amigo/global_planner/global_costmap/track_unknown_space: False
 * /amigo/global_planner/global_costmap/update_frequency: 1.0
 * /amigo/local_planner/DWAPlannerROS/acc_lim_th: 0.5
 * /amigo/local_planner/DWAPlannerROS/acc_lim_x: 0.35
 * /amigo/local_planner/DWAPlannerROS/acc_lim_y: 0.35
 * /amigo/local_planner/DWAPlannerROS/acc_limit_trans: 0.35
 * /amigo/local_planner/DWAPlannerROS/align_align_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_nth: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_nx: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_ny: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_pth: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_px: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_py: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_goal_scale: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_obstacle_scale: 0.1
 * /amigo/local_planner/DWAPlannerROS/align_plan_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/angular_sim_granularity: 0.1
 * /amigo/local_planner/DWAPlannerROS/arrive_align_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_nth: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_nx: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_ny: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_pth: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_px: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_py: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_goal_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/arrive_obstacle_scale: 0.01
 * /amigo/local_planner/DWAPlannerROS/arrive_plan_scale: 0.0
 * /amigo/local_planner/DWAPlannerROS/deacc_limit_trans: 0.5
 * /amigo/local_planner/DWAPlannerROS/default_align_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_nth: 0.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_nx: 100.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_ny: 25.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_pth: 0.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_px: 0.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_py: 25.0
 * /amigo/local_planner/DWAPlannerROS/default_goal_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/default_obstacle_scale: 0.03
 * /amigo/local_planner/DWAPlannerROS/default_plan_scale: 0.0
 * /amigo/local_planner/DWAPlannerROS/max_rot_vel: 1.0
 * /amigo/local_planner/DWAPlannerROS/max_trans_vel: 0.7
 * /amigo/local_planner/DWAPlannerROS/max_vel_x: 0.7
 * /amigo/local_planner/DWAPlannerROS/max_vel_y: 0.2
 * /amigo/local_planner/DWAPlannerROS/min_rot_vel: 0.1
 * /amigo/local_planner/DWAPlannerROS/min_trans_vel: 0.0
 * /amigo/local_planner/DWAPlannerROS/min_vel_x: -0.1
 * /amigo/local_planner/DWAPlannerROS/min_vel_y: -0.2
 * /amigo/local_planner/DWAPlannerROS/prune_plan: True
 * /amigo/local_planner/DWAPlannerROS/rot_stopped_vel: 0.1
 * /amigo/local_planner/DWAPlannerROS/sim_granularity: 0.1
 * /amigo/local_planner/DWAPlannerROS/sim_period: 0.1
 * /amigo/local_planner/DWAPlannerROS/sim_time: 2.5
 * /amigo/local_planner/DWAPlannerROS/switch_goal_distance: 0.3
 * /amigo/local_planner/DWAPlannerROS/switch_plan_distance: 0.5
 * /amigo/local_planner/DWAPlannerROS/switch_yaw_error: 1.6
 * /amigo/local_planner/DWAPlannerROS/trans_stopped_vel: 0.1
 * /amigo/local_planner/DWAPlannerROS/use_dwa: True
 * /amigo/local_planner/DWAPlannerROS/vth_samples: 10
 * /amigo/local_planner/DWAPlannerROS/vx_samples: 4
 * /amigo/local_planner/DWAPlannerROS/vy_samples: 10
 * /amigo/local_planner/DWAPlannerROS/xy_goal_tolerance: 0.1
 * /amigo/local_planner/DWAPlannerROS/yaw_goal_tolerance: 0.1
 * /amigo/local_planner/controller_frequency: 10.0
 * /amigo/local_planner/global_frame: /map
 * /amigo/local_planner/local_costmap/always_send_full_costmap: True
 * /amigo/local_planner/local_costmap/configuration_space/cost_scaling_factor: 5.0
 * /amigo/local_planner/local_costmap/configuration_space/dilation_cell_value: 253
 * /amigo/local_planner/local_costmap/configuration_space/dilation_radius: 0.35
 * /amigo/local_planner/local_costmap/configuration_space/inflation_radius: 1.0
 * /amigo/local_planner/local_costmap/configuration_space/target_cell_value: 254
 * /amigo/local_planner/local_costmap/configuration_space/use_footprint: False
 * /amigo/local_planner/local_costmap/ed_occupancy_grid/lethal_cost_threshold: 99
 * /amigo/local_planner/local_costmap/ed_occupancy_grid/map_topic: /amigo/ed/navigat...
 * /amigo/local_planner/local_costmap/ed_occupancy_grid/track_unknown_space: True
 * /amigo/local_planner/local_costmap/ed_occupancy_grid/use_maximum: True
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/dilation_cell_value: 253
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/dilation_radius: 0.2
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/inflation_radius: 0.2
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/target_cell_value: 254
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/use_footprint: False
 * /amigo/local_planner/local_costmap/free_space_inflation/dilation_cell_value: 170
 * /amigo/local_planner/local_costmap/free_space_inflation/dilation_radius: 1.1
 * /amigo/local_planner/local_costmap/free_space_inflation/inflation_radius: 1.1
 * /amigo/local_planner/local_costmap/free_space_inflation/target_cell_value: 255
 * /amigo/local_planner/local_costmap/free_space_inflation/use_footprint: False
 * /amigo/local_planner/local_costmap/global_frame: /map
 * /amigo/local_planner/local_costmap/height: 4.0
 * /amigo/local_planner/local_costmap/plugins: [{'type': 'costma...
 * /amigo/local_planner/local_costmap/publish_frequency: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/clearing: False
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/data_type: LaserScan
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/inf_is_valid: True
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/marking: True
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/observation_persistence: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/obstacle_range: 10.0
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/ray_trace_range: 10.0
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/sensor_frame: /amigo/base_laser
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/topic: /amigo/base_laser...
 * /amigo/local_planner/local_costmap/recent_obstacles/observation_sources: base_laser torso_...
 * /amigo/local_planner/local_costmap/recent_obstacles/occupied_to_default_time: 2.0
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/data_type: PointCloud2
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/expected_update_rate: 1.0
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/max_obstacle_height: 0.5
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/min_obstacle_height: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/observation_persistence: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/obstacle_range: 10
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/sensor_frame: /amigo/top_kinect...
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/topic: /amigo/ed/navigat...
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/clearing: False
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/data_type: LaserScan
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/inf_is_valid: True
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/marking: True
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/observation_persistence: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/obstacle_range: 10.0
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/ray_trace_range: 10.0
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/sensor_frame: /amigo/torso_laser
 * /amigo/local_planner/local_costmap/recent_obstacles/torso_laser/topic: /amigo/torso_lase...
 * /amigo/local_planner/local_costmap/resolution: 0.025
 * /amigo/local_planner/local_costmap/robot_base_frame: /amigo/base_link
 * /amigo/local_planner/local_costmap/robot_radius: 0.35
 * /amigo/local_planner/local_costmap/rolling_window: True
 * /amigo/local_planner/local_costmap/track_unknown_space: False
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/clearing: True
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/data_type: LaserScan
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/inf_is_valid: True
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/marking: False
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/observation_persistence: 0.0
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/ostacle_range: 20.0
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/ray_trace_range: 20.0
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/sensor_frame: /amigo/base_laser
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/topic: /amigo/base_laser...
 * /amigo/local_planner/local_costmap/unknown_free_space/combination_method: 1
 * /amigo/local_planner/local_costmap/unknown_free_space/footprint_scale: 1.5
 * /amigo/local_planner/local_costmap/unknown_free_space/free_to_default_time: 30.0
 * /amigo/local_planner/local_costmap/unknown_free_space/observation_sources: base_laser
 * /amigo/local_planner/local_costmap/unknown_free_space/track_unknown_space: True
 * /amigo/local_planner/local_costmap/update_frequency: 0.0
 * /amigo/local_planner/local_costmap/width: 4.0
 * /amigo/local_planner/local_planner: dwa_local_planner...
 * /amigo/local_planner/robot_base_frame: /amigo/base_link
 * /amigo/object_recognition/graph_path: ~/MEGA/data/robot...
 * /amigo/object_recognition/labels_path: ~/MEGA/data/robot...
 * /amigo/object_recognition/save_images: True
 * /amigo/object_recognition/save_images_folder: ~/MEGA/data/robot...
 * /rosdistro: kinetic
 * /rosversion: 1.12.6

NODES
  /amigo/
    ed (ed/ed)
    ed_configure (ed/configure)
    face_recognition (openface_ros/face_recognition_node)
    global_planner (cb_base_navigation/cb_base_navigation_global_planner_interface)
    local_planner (cb_base_navigation/cb_base_navigation_local_planner_interface)
    object_recognition (tensorflow_ros/object_recognition_node)
  /
    state_machine (challenge_spr/challenge_spr.py)

ROS_MASTER_URI=http://amigo1:11311

core service [/rosout] found
process[amigo/local_planner-1]: started with pid [4358]
process[amigo/global_planner-2]: started with pid [4359]
process[amigo/ed-3]: started with pid [4363]
process[amigo/ed_configure-4]: started with pid [4368]
process[amigo/face_recognition-5]: started with pid [4369]
process[amigo/object_recognition-6]: started with pid [4372]
process[state_machine-7]: started with pid [4373]
[amigo/ed_configure-4] process has finished cleanly
log file: /home/amigo/.ros/log/1e26d58e-1c5c-11e7-a82e-00031d0a0d6c/amigo-ed_configure-4*.log
[INFO] [1491664644.783385]: Using robot 'amigo'.
[ERROR] [1491664644.807813]: Could not find record_robocup.launch in bringup package of robot amigo
/home/amigo/ros/kinetic/system/src/smach_ros/src/smach_ros/introspection.py:132: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  data_class=SmachContainerStructure)
/home/amigo/ros/kinetic/system/src/smach_ros/src/smach_ros/introspection.py:137: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  data_class=SmachContainerStatus)
[INFO] [1491664646.250859]: State machine starting in initial state 'INITIALIZE' with userdata: 
	[]
[INFO] [1491664646.474898]: TF link between /map and /base_link is checked. If it takes longer than a second, probably an error. Do a restart!!!
[INFO] [1491664646.551227]: State machine transitioning 'INITIALIZE':'initialized'-->'ANNOUNCEMENT'
[INFO] [1491664646.552019]: 'I want to play a riddle game'
[INFO] [1491664648.453671]: State machine transitioning 'ANNOUNCEMENT':'spoken'-->'WAIT'
[INFO] [1491664658.568519]: State machine transitioning 'WAIT':'waited'-->'TURN'
Turning 3.141593 radians with force drive at 1.000000 rad/s
[ERROR] [1491664658.569223]: Called get_state when no goal is running
[INFO] [1491664661.778446]: State machine transitioning 'TURN':'turned'-->'DETECT_CROWD'
[INFO] [1491664661.779300]: 'You are all looking great today!            Keep looking in my camera!'
[INFO] [1491664663.310736]: Getting one image
[INFO] [1491664663.318070]: waiting...
[INFO] [1491664663.440940]: Image data callback
[INFO] [1491664663.443797]: Got data
[INFO] [1491664664.552330]: Faces: [RecognizedFace(roi=(340, 227, 153, 179), l2_distances=[]), RecognizedFace(roi=(698, 155, 153, 179), l2_distances=[])]
[INFO] [1491664664.565050]: 'I like it when everybody is staring at me; being in the center of attention!'
[INFO] [1491664665.998614]: Getting one image
[INFO] [1491664666.001803]: waiting...
[INFO] [1491664666.077644]: Image data callback
[INFO] [1491664666.080690]: Got data
[INFO] [1491664667.175140]: Faces: [RecognizedFace(roi=(343, 237, 127, 149), l2_distances=[]), RecognizedFace(roi=(669, 141, 153, 179), l2_distances=[])]
[INFO] [1491664667.185535]: 'You are all looking great today!            Keep looking in my camera!'
[INFO] [1491664668.622996]: Getting one image
[INFO] [1491664668.626376]: waiting...
[INFO] [1491664668.704746]: Image data callback
[INFO] [1491664668.707639]: Got data
[INFO] [1491664669.828734]: Faces: [RecognizedFace(roi=(331, 225, 127, 149), l2_distances=[]), RecognizedFace(roi=(669, 155, 153, 179), l2_distances=[])]
[INFO] [1491664669.832415]: Calling Skybiometry...
[INFO] [1491664674.048493]: face_properties:
 - gender: 0
age: 31
 - gender: 0
age: 23
[INFO] [1491664674.049035]: 'There are 2 males and 0 females in the crowd'
[INFO] [1491664677.090666]: State machine transitioning 'DETECT_CROWD':'succeeded'-->'REQUEST_OPERATOR'
[INFO] [1491664677.091340]: 'Who wants to play riddles with me?'
[INFO] [1491664679.133396]: State machine transitioning 'REQUEST_OPERATOR':'spoken'-->'WAIT_FOR_OPERATOR'
WaitForDesignator: waiting 0/1
[ERROR] [1491664679.149481]: No entities found in 

Designator(
  center_point = [           0,           0,           0] @ /map
  center_point_designator = None
  criteriafuncs = []
  debug = False
  ed = <robot_skills.world_model_ed.ED object at 0x7f28402d3590>
  id = 
  id_designator = None
  lockable = <bound method EdEntityDesignator.lockable of Designator(resolve_type=<class 'robot_skills.util.entity.Entity'>, name=None)>
  name = None
  radius = 0
  resolve_type = <class 'robot_skills.util.entity.Entity'>
  robot = <robot_skills.amigo.Amigo object at 0x7f2840412bd0>
  type = human
  type_designator = None
  weight_function = <function <lambda> at 0x7f28401c2b90>)


[INFO] [1491664680.150991]: State machine transitioning 'WAIT_FOR_OPERATOR':'failed'-->'RIDDLE_GAME_1'
[INFO] [1491664680.152221]: spec: <question>
[INFO] [1491664680.153208]: Example: 'How many males are there in the crowd?'
[INFO] [1491664695.169762]: Preempt finished within specified preempt_timeout [1.00]
[INFO] [1491664695.170216]: Robot did not hear you (timeout)
[INFO] [1491664695.170617]: 'Sorry, I do not understand your question'
[ERROR] [1491664698.139713]: InvalidTransitionError: Attempted to return outcome 'not_answered' from state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f2840179850>' which only has registered outcomes: ('answered',)
[ERROR] [1491664698.140206]: Robot exited with <class 'smach.exceptions.InvalidTransitionError'>,Attempted to return outcome 'not_answered' from state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f2840179850>' which only has registered outcomes: ('answered',),<traceback object at 0x7f28401a4128>
[INFO] [1491664698.140686]: Torso cancelling all goals on close
[INFO] [1491664698.141075]: left arm cancelling all goals on all arm-related ACs on close
[INFO] [1491664698.141593]: right arm cancelling all goals on all arm-related ACs on close
Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/challenge_spr/src/challenge_spr.py", line 107, in <module>
    startup(ChallengeSpeechPersonRecognition, challenge_name="challenge_spr")
  File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/util/startup.py", line 91, in startup
    outcome = executioner.execute()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 266, in _update_once
    self._current_state.get_registered_outcomes()))
smach.exceptions.InvalidTransitionError: Attempted to return outcome 'not_answered' from state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f2840179850>' which only has registered outcomes: ('answered',)
^C[state_machine-7] killing on exit
[amigo/object_recognition-6] killing on exit
[amigo/global_planner-2] killing on exit
[amigo/face_recognition-5] killing on exit
[amigo/ed-3] killing on exit
[amigo/local_planner-1] killing on exit
^C
^Z
[1]+  Stopped                 roslaunch challenge_spr.launch

**Comment by MatthijsBurgh** [comment]
This is cause by missing a possible outcome in https://github.com/tue-robotics/tue_robocup/blob/feature/challenge-spr/challenge_spr/src/challenge_spr_states/riddle_game.py#L54.

This outcome needs to be added in the main challenge, and in the test state machine
