### ISSUE TITLE
self._robot.ed.learn_person(self._operator_name) method disappeared!, returning False

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#240]
We are using a new person recognition backend now, but this is not yet migrated.

**Comment by MatthijsBurgh** [comment]
Is this migrated correct?

**Comment by LoyVanBeek** [comment]
@Rayman has the latest news I think

**Comment by Rayman** [comment]
Just use `robot.head.learn_person()`. I don't know in how many places this should be fixed. I'll put it on the ToDo list

**Comment by Rayman** [comment]
The `LearnPerson` and `FollowOperator` are using the new API so this is finished. I'll create a new PR to clean up the old deprecation error
