### ISSUE TITLE
Project yaw angle of a 3d rotation

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_robocup#260]
If there are also nonzero roll and pitch angles, this will generally not return the correct projected yaw angle as the other angles may also influence this.
I've so far seen this in 
https://github.com/tue-robotics/tue_robocup/blob/master/robot_smach_states/src/robot_smach_states/navigation/navigate_to_grasp.py#L62 
and 
https://github.com/tue-robotics/tue_robocup/blob/master/robot_smach_states/src/robot_smach_states/navigation/navigate_to_waypoint.py#L42

**Comment by MatthijsBurgh** [comment]
What is the status?

**Comment by Rayman** [comment]
@rokusottervanger, what do you want to do about this?

**Comment by MatthijsBurgh** [comment]
@rokusottervanger and I had a small discussion 1 a 2 weeks ago. GetRPY instead of GetEulerZYX, should solve the problem.

**Comment by rokusottervanger** [comment]
You can fix this if you like, @MatthijsBurgh

**Comment by MatthijsBurgh** [comment]
GetRPY is not the solution as GetEulerZYX returns GetRPY: http://docs.ros.org/jade/api/orocos_kdl/html/frames_8hpp_source.html#l00493
