### ISSUE TITLE
FollowOperator: looking for lost operator takes too long without success

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#272]
This line: https://github.com/tue-robotics/tue_robocup/blob/master/robot_smach_states/src/robot_smach_states/navigation/follow_operator.py#L456

takes a minute but even when directly looking at me, it doesn't recognize and continue

**Comment by LoyVanBeek** [comment]
Addressed in https://github.com/tue-robotics/tue_robocup/pull/287

**Comment by MatthijsBurgh** [comment]
This is still not working. Last example, the fanday

**Comment by LoyVanBeek** [comment]
The PR is not yet merged because it doe snot work on that branch yet either.
