### ISSUE TITLE
[Navigation] Paths are blocked by ghost entities

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_robocup#28]
Entities are found above a relevant height level. These block the paths so that the challenge is ended prematurely

**Comment by reinzor** [comment]
This is an ED  issue, we should add min max z values to sensor integration plugins to cut off the sensor data to prevent ceiling modeling. Furthermore, the occupancy grid publisher should have a min and max z or take the robots height into account.

-Rein

**Comment by rokusottervanger** [comment]
Fixed by tue-robotics/ed_sensor_integration@c20fe2d28bd69bfd25083f3525f3c2f542c27aec
