### ISSUE TITLE
Check status of robot Bodyparts at challenge start

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#283]
For each bodypart, report when they are idle.

Do not block on this, just report and continue, as suggested by @MaxBaeten 
After this report, the operator must take action.

**Comment by MatthijsBurgh** [comment]
PR is merged, so done? @LoyVanBeek

**Comment by LoyVanBeek** [comment]
The merged R is about the e-stop, not all other body parts. So not yet done but n=does not have high prio either.

**Comment by LoyVanBeek** [comment]
With the SSL on a separate board that's hard to see the status of, this is bound to go wrong sometime...

**Comment by MatthijsBurgh** [comment]
Checking on publishing can be tricky, because it only publishes, when a new detection is received.

**Comment by LoyVanBeek** [comment]
I know. I just check if there is at least one publisher on the topic, not counting messages
