### ISSUE TITLE
Fanday

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#300]
- [x] Clicked point @Rayman (https://github.com/tue-robotics/tue_robocup/pull/302)
- [x] Old open challenge @MatthijsBurgh 
- [ ] Removing walls from WM @MatthijsBurgh

**Comment by MatthijsBurgh** [comment]
Old open challenge is working as far as I tested. I only need to fix the implementation of the action server in combination with trigger.
