### ISSUE TITLE
GPSR: crashes

### ISSUE THREAD

**Issue by svddries** [tue-robotics/tue_robocup#31]
[WARN] [WallTime: 1426003703.814611] ToDo: Close grippers
[INFO] [WallTime: 1426003703.814860] Send torso goal [0.8, 2.0, 2.1], timeout = 0.0
[WARN] [WallTime: 1426003703.815316] ToDo: Reset costmap and reasoner
[INFO] [WallTime: 1426003703.815873] TF link between /map and /base_link is checked. If it takes longer than a second, probably an error. Do a restart!!!
[WARN] [WallTime: 1426003703.818389] ToDo: Load correct perception config???
[INFO] [WallTime: 1426003703.818709] State machine transitioning 'INITIALIZE':'initialized'-->'ASK_ACTION'
[INFO] [WallTime: 1426003703.819253] 'What can I do for you?'
[INFO] [WallTime: 1426003717.046055] 'Sorry, could you please repeat?'
[INFO] [WallTime: 1426003720.415192] State machine transitioning 'ASK_ACTION':'done'-->'QUERY_SPECIFIC_ACTION'
[ERROR] [WallTime: 1426003720.420641] InvalidTransitionError: Attempted to return outcome 'None' from state 'QUERY_SPECIFIC_ACTION' of type '<__main__.Query_specific_action object at 0x3451dd0>' which only has registered outcomes: ('test',)
[ERROR] [WallTime: 1426003720.420922] Robot exited with smach.exceptions.InvalidTransitionError,<smach.exceptions.InvalidTransitionError instance at 0x344fc20>,<traceback object at 0x345b830>
[INFO] [WallTime: 1426003720.421175] Torso cancelling all goals on close
[INFO] [WallTime: 1426003720.421461] left arm cancelling all goals on all arm-related ACs on close
[INFO] [WallTime: 1426003720.421988] right arm cancelling all goals on all arm-related ACs on close
Traceback (most recent call last):
  File "/home/amigo/ros/hydro/system/src/challenge_gpsr/src/challenge_gpsr/gpsr.py", line 282, in <module>
    states.util.startup(setup_statemachine, robot_name=robot_name)
  File "/home/amigo/ros/hydro/system/src/robot_smach_states/src/robot_smach_states/util/startup.py", line 69, in startup
    outcome = executioner.execute()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 347, in execute
    container_outcome = self._update_once()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 256, in _update_once
    str(self._current_state.get_registered_outcomes())))
smach.exceptions.InvalidTransitionError: <smach.exceptions.InvalidTransitionError instance at 0x344fc20>

**Comment by egeerts** [comment]
fixed
