### ISSUE TITLE
Trigger CI build when dependency is updated

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#314]
Can be done perhaps via http://eng.rightscale.com/2015/04/27/dependent-builds-in-travis.html or https://github.com/mernst/plume-lib/blob/master/bin/trigger-travis.sh
i.e. the dependencies trigger a build of it's dependents. 

To determine at least some dependencies, we might use ```rospack depends-on```

**Comment by Timple** [comment]
Stable enough? https://travis-ci.org/tue-robotics

**Comment by LoyVanBeek** [comment]
The software isn't tested as rigorously as we want, though it likely never will be. Triggering other builds is a good test.

**Comment by Rayman** [comment]
>The Travis API doesn’t currently support creating a new build, but we can be a little creative. 

Dependent builds look like giant hack to me
