### ISSUE TITLE
crash in SPR

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/tue_robocup#317]
amigo@amigo2 $ amigo-challenge-spr 
... logging to /home/amigo/.ros/log/f8cc9ea0-5049-11e7-ba3a-00031d0a0d6c/roslaunch-amigo2-18128.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://amigo2:39176/

SUMMARY
========

PARAMETERS
 * /amigo/face_recognition/face_recognition/align_path: ~/openface/models...
 * /amigo/face_recognition/face_recognition/db: 
 * /amigo/face_recognition/face_recognition/net_path: ~/openface/models...
 * /amigo/face_recognition/face_recognition/save_images: True
 * /amigo/face_recognition/face_recognition/save_images_folder: ~/MEGA/data/robot...
 * /amigo/global_planner/base_global_planner: base_navigation::...
 * /amigo/global_planner/global_costmap/always_send_full_costmap: True
 * /amigo/global_planner/global_costmap/configuration_space/dilation_cell_value: 253
 * /amigo/global_planner/global_costmap/configuration_space/dilation_radius: 0.37
 * /amigo/global_planner/global_costmap/configuration_space/inflation_radius: 0.6
 * /amigo/global_planner/global_costmap/configuration_space/target_cell_value: 254
 * /amigo/global_planner/global_costmap/configuration_space/use_footprint: False
 * /amigo/global_planner/global_costmap/ed_occupancy_grid/map_topic: /amigo/ed/navigat...
 * /amigo/global_planner/global_costmap/ed_occupancy_grid/track_unknown_space: False
 * /amigo/global_planner/global_costmap/global_frame: /map
 * /amigo/global_planner/global_costmap/plugins: [{'type': 'costma...
 * /amigo/global_planner/global_costmap/publish_frequency: 1.0
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/clearing: False
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/data_type: LaserScan
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/inf_is_valid: True
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/marking: True
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/observation_persistence: 0.0
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/obstacle_range: 10.0
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/ray_trace_range: 10.0
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/sensor_frame: /amigo/base_laser
 * /amigo/global_planner/global_costmap/recent_obstacles/base_laser/topic: /amigo/base_laser...
 * /amigo/global_planner/global_costmap/recent_obstacles/observation_sources: base_laser top_ki...
 * /amigo/global_planner/global_costmap/recent_obstacles/occupied_to_default_time: 2.0
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/data_type: PointCloud2
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/expected_update_rate: 1.0
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/max_obstacle_height: 0.5
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/min_obstacle_height: 0.0
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/observation_persistence: 0.0
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/obstacle_range: 10
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/sensor_frame: /amigo/top_kinect...
 * /amigo/global_planner/global_costmap/recent_obstacles/top_kinect/topic: /amigo/ed/navigat...
 * /amigo/global_planner/global_costmap/resolution: 0.05
 * /amigo/global_planner/global_costmap/robot_base_frame: /amigo/base_link
 * /amigo/global_planner/global_costmap/rolling_window: False
 * /amigo/global_planner/global_costmap/track_unknown_space: False
 * /amigo/global_planner/global_costmap/update_frequency: 1.0
 * /amigo/local_planner/DWAPlannerROS/acc_lim_th: 0.5
 * /amigo/local_planner/DWAPlannerROS/acc_lim_x: 0.35
 * /amigo/local_planner/DWAPlannerROS/acc_lim_y: 0.35
 * /amigo/local_planner/DWAPlannerROS/acc_limit_trans: 0.35
 * /amigo/local_planner/DWAPlannerROS/align_align_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_nth: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_nx: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_ny: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_pth: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_px: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_cmd_py: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_goal_scale: 0.0
 * /amigo/local_planner/DWAPlannerROS/align_obstacle_scale: 0.1
 * /amigo/local_planner/DWAPlannerROS/align_plan_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/angular_sim_granularity: 0.1
 * /amigo/local_planner/DWAPlannerROS/arrive_align_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_nth: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_nx: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_ny: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_pth: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_px: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_cmd_py: 0.0
 * /amigo/local_planner/DWAPlannerROS/arrive_goal_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/arrive_obstacle_scale: 0.01
 * /amigo/local_planner/DWAPlannerROS/arrive_plan_scale: 0.0
 * /amigo/local_planner/DWAPlannerROS/deacc_limit_trans: 0.5
 * /amigo/local_planner/DWAPlannerROS/default_align_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_nth: 0.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_nx: 100.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_ny: 25.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_pth: 0.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_px: 0.0
 * /amigo/local_planner/DWAPlannerROS/default_cmd_py: 25.0
 * /amigo/local_planner/DWAPlannerROS/default_goal_scale: 1.0
 * /amigo/local_planner/DWAPlannerROS/default_obstacle_scale: 0.03
 * /amigo/local_planner/DWAPlannerROS/default_plan_scale: 0.0
 * /amigo/local_planner/DWAPlannerROS/max_rot_vel: 1.0
 * /amigo/local_planner/DWAPlannerROS/max_trans_vel: 0.7
 * /amigo/local_planner/DWAPlannerROS/max_vel_x: 0.7
 * /amigo/local_planner/DWAPlannerROS/max_vel_y: 0.2
 * /amigo/local_planner/DWAPlannerROS/min_rot_vel: 0.1
 * /amigo/local_planner/DWAPlannerROS/min_trans_vel: 0.0
 * /amigo/local_planner/DWAPlannerROS/min_vel_x: -0.1
 * /amigo/local_planner/DWAPlannerROS/min_vel_y: -0.2
 * /amigo/local_planner/DWAPlannerROS/prune_plan: True
 * /amigo/local_planner/DWAPlannerROS/rot_stopped_vel: 0.1
 * /amigo/local_planner/DWAPlannerROS/sim_granularity: 0.1
 * /amigo/local_planner/DWAPlannerROS/sim_period: 0.1
 * /amigo/local_planner/DWAPlannerROS/sim_time: 2.5
 * /amigo/local_planner/DWAPlannerROS/switch_goal_distance: 0.3
 * /amigo/local_planner/DWAPlannerROS/switch_plan_distance: 0.5
 * /amigo/local_planner/DWAPlannerROS/switch_yaw_error: 1.6
 * /amigo/local_planner/DWAPlannerROS/trans_stopped_vel: 0.1
 * /amigo/local_planner/DWAPlannerROS/use_dwa: True
 * /amigo/local_planner/DWAPlannerROS/vth_samples: 10
 * /amigo/local_planner/DWAPlannerROS/vx_samples: 4
 * /amigo/local_planner/DWAPlannerROS/vy_samples: 10
 * /amigo/local_planner/DWAPlannerROS/xy_goal_tolerance: 0.1
 * /amigo/local_planner/DWAPlannerROS/yaw_goal_tolerance: 0.1
 * /amigo/local_planner/controller_frequency: 10.0
 * /amigo/local_planner/global_frame: /map
 * /amigo/local_planner/local_costmap/always_send_full_costmap: True
 * /amigo/local_planner/local_costmap/configuration_space/cost_scaling_factor: 5.0
 * /amigo/local_planner/local_costmap/configuration_space/dilation_cell_value: 253
 * /amigo/local_planner/local_costmap/configuration_space/dilation_radius: 0.35
 * /amigo/local_planner/local_costmap/configuration_space/inflation_radius: 1.0
 * /amigo/local_planner/local_costmap/configuration_space/target_cell_value: 254
 * /amigo/local_planner/local_costmap/configuration_space/use_footprint: False
 * /amigo/local_planner/local_costmap/ed_occupancy_grid/lethal_cost_threshold: 99
 * /amigo/local_planner/local_costmap/ed_occupancy_grid/map_topic: /amigo/ed/navigat...
 * /amigo/local_planner/local_costmap/ed_occupancy_grid/track_unknown_space: True
 * /amigo/local_planner/local_costmap/ed_occupancy_grid/use_maximum: True
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/dilation_cell_value: 253
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/dilation_radius: 0.2
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/inflation_radius: 0.2
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/target_cell_value: 254
 * /amigo/local_planner/local_costmap/eliminate_small_occlusions/use_footprint: False
 * /amigo/local_planner/local_costmap/free_space_inflation/dilation_cell_value: 170
 * /amigo/local_planner/local_costmap/free_space_inflation/dilation_radius: 1.1
 * /amigo/local_planner/local_costmap/free_space_inflation/inflation_radius: 1.1
 * /amigo/local_planner/local_costmap/free_space_inflation/target_cell_value: 255
 * /amigo/local_planner/local_costmap/free_space_inflation/use_footprint: False
 * /amigo/local_planner/local_costmap/global_frame: /map
 * /amigo/local_planner/local_costmap/height: 4.0
 * /amigo/local_planner/local_costmap/plugins: [{'type': 'costma...
 * /amigo/local_planner/local_costmap/publish_frequency: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/clearing: False
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/data_type: LaserScan
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/inf_is_valid: True
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/marking: True
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/observation_persistence: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/obstacle_range: 10.0
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/ray_trace_range: 10.0
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/sensor_frame: /amigo/base_laser
 * /amigo/local_planner/local_costmap/recent_obstacles/base_laser/topic: /amigo/base_laser...
 * /amigo/local_planner/local_costmap/recent_obstacles/observation_sources: base_laser top_ki...
 * /amigo/local_planner/local_costmap/recent_obstacles/occupied_to_default_time: 2.0
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/data_type: PointCloud2
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/expected_update_rate: 1.0
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/max_obstacle_height: 0.5
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/min_obstacle_height: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/observation_persistence: 0.0
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/obstacle_range: 10
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/sensor_frame: /amigo/top_kinect...
 * /amigo/local_planner/local_costmap/recent_obstacles/top_kinect/topic: /amigo/ed/navigat...
 * /amigo/local_planner/local_costmap/resolution: 0.025
 * /amigo/local_planner/local_costmap/robot_base_frame: /amigo/base_link
 * /amigo/local_planner/local_costmap/robot_radius: 0.35
 * /amigo/local_planner/local_costmap/rolling_window: True
 * /amigo/local_planner/local_costmap/track_unknown_space: False
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/clearing: True
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/data_type: LaserScan
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/inf_is_valid: True
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/marking: False
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/observation_persistence: 0.0
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/ostacle_range: 20.0
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/ray_trace_range: 20.0
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/sensor_frame: /amigo/base_laser
 * /amigo/local_planner/local_costmap/unknown_free_space/base_laser/topic: /amigo/base_laser...
 * /amigo/local_planner/local_costmap/unknown_free_space/combination_method: 1
 * /amigo/local_planner/local_costmap/unknown_free_space/footprint_scale: 1.5
 * /amigo/local_planner/local_costmap/unknown_free_space/free_to_default_time: 30.0
 * /amigo/local_planner/local_costmap/unknown_free_space/observation_sources: base_laser
 * /amigo/local_planner/local_costmap/unknown_free_space/track_unknown_space: True
 * /amigo/local_planner/local_costmap/update_frequency: 0.0
 * /amigo/local_planner/local_costmap/width: 4.0
 * /amigo/local_planner/local_planner: dwa_local_planner...
 * /amigo/local_planner/robot_base_frame: /amigo/base_link
 * /amigo/object_recognition/object_recognition/graph_path: ~/MEGA/data/robot...
 * /amigo/object_recognition/object_recognition/labels_path: ~/MEGA/data/robot...
 * /amigo/object_recognition/object_recognition/save_images: True
 * /amigo/object_recognition/object_recognition/save_images_folder: ~/MEGA/data/robot...
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /skybiometry_face_properties/api_timeout: 60

NODES
  /amigo/object_recognition/
    object_recognition (tensorflow_ros/object_recognition_node)
  /amigo/
    ed (ed/ed)
    ed_configure (ed/configure)
    global_planner (cb_base_navigation/cb_base_navigation_global_planner_interface)
    local_planner (cb_base_navigation/cb_base_navigation_local_planner_interface)
  /
    skybiometry_face_properties (skybiometry_ros/face_properties_node)
    state_machine (challenge_spr/challenge_spr.py)
  /amigo/face_recognition/
    face_recognition (openface_ros/face_recognition_node)

ROS_MASTER_URI=http://amigo1:11311

core service [/rosout] found
process[amigo/local_planner-1]: started with pid [18137]
process[amigo/global_planner-2]: started with pid [18138]
process[amigo/ed-3]: started with pid [18143]
process[amigo/ed_configure-4]: started with pid [18149]
process[amigo/face_recognition/face_recognition-5]: started with pid [18151]
process[amigo/object_recognition/object_recognition-6]: started with pid [18152]
process[skybiometry_face_properties-7]: started with pid [18156]
process[state_machine-8]: started with pid [18159]
[amigo/ed_configure-4] process has finished cleanly
log file: /home/amigo/.ros/log/f8cc9ea0-5049-11e7-ba3a-00031d0a0d6c/amigo-ed_configure-4*.log
[ERROR] [1497368018.442942]: /amigo/person_detection/detect_persons not connected timely
[INFO] [1497368018.895125]: Using robot 'amigo'.
... logging to /home/amigo/.ros/log/f8cc9ea0-5049-11e7-ba3a-00031d0a0d6c/roslaunch-amigo2-18159.log
started roslaunch server http://amigo2:44215/
remote[amigo1-0] starting roslaunch
remote[amigo1-0]: creating ssh connection to amigo1:22, user[amigo]
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
launching remote roslaunch child with command: [env ROS_MASTER_URI=http://amigo1:11311 /home/amigo/.ros-bash-and-run.sh roslaunch -c amigo1-0 -u http://amigo2:44215/ --run_id f8cc9ea0-5049-11e7-ba3a-00031d0a0d6c]
remote[amigo1-0]: ssh connection created

SUMMARY
========

PARAMETERS
 * /amigo/record/audio_capture/bitrate: 128
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

MACHINES
 * amigo1

NODES
  /amigo/record/
    audio_capture (audio_capture/audio_capture)
  /amigo/
    record_relay_base_plan (topic_tools/relay)
    record_relay_body_plan (topic_tools/relay)
    record_throttle_base_laser (topic_tools/throttle)
    record_throttle_ed_map (topic_tools/throttle)
    record_throttle_gmapping_map (topic_tools/throttle)
    record_throttle_odom (topic_tools/throttle)
    record_throttle_tf (topic_tools/throttle)
    robcup_recorder (rosbag/record)
  /amigo/hmi/
    hmi_logger (test_tools/hmi_logger.py)

ROS_MASTER_URI=http://amigo1:11311
core service [/rosout] found
[amigo1-0]: launching nodes...
[amigo1-0]: ROS_MASTER_URI=http://amigo1:11311
[amigo1-0]: process[amigo/hmi/hmi_logger-1]: started with pid [23682]
[amigo1-0]: process[amigo/record/audio_capture-2]: started with pid [23683]
[amigo1-0]: process[amigo/record_throttle_tf-3]: started with pid [23684]
[amigo1-0]: process[amigo/record_throttle_ed_map-4]: started with pid [23694]
[amigo1-0]: process[amigo/record_throttle_gmapping_map-5]: started with pid [23727]
[amigo1-0]: process[amigo/record_relay_base_plan-6]: started with pid [23749]
[amigo1-0]: process[amigo/record_relay_body_plan-7]: started with pid [23778]
[amigo1-0]: process[amigo/record_throttle_odom-8]: started with pid [23790]
[amigo1-0]: process[amigo/record_throttle_base_laser-9]: started with pid [23807]
[amigo1-0]: process[amigo/robcup_recorder-10]: started with pid [23825]
[amigo1-0]: ... done launching nodes
[INFO] [1497368021.634028]: State machine starting in initial state 'INITIALIZE' with userdata: 
	[]
[INFO] [1497368021.872431]: TF link between /map and /base_link is checked. If it takes longer than a second, probably an error. Do a restart!!!
[INFO] [1497368021.908909]: State machine transitioning 'INITIALIZE':'initialized'-->'ANNOUNCEMENT'
[INFO] [1497368021.909245]: 'I want to play a riddle game'
[INFO] [1497368027.073281]: State machine transitioning 'ANNOUNCEMENT':'spoken'-->'WAIT'
[INFO] [1497368037.186558]: State machine transitioning 'WAIT':'waited'-->'TURN'
Turning 3.141593 radians with force drive at 1.000000 rad/s
[ERROR] [1497368037.186763]: Called get_state when no goal is running
[INFO] [1497368040.396118]: State machine transitioning 'TURN':'turned'-->'DETECT_CROWD'
[INFO] [1497368040.396386]: 'You are all looking great today!            Keep looking in my camera!'
[INFO] [1497368042.228275]: lazy subscribe to /amigo/top_kinect/rgb/image
[INFO] [1497368042.228512]: getting one image...
[INFO] [1497368042.397566]: got 3932160 bytes of image data
[INFO] [1497368043.551248]: Faces: []
[INFO] [1497368043.557736]: 'I like it when everybody is staring at me; being in the center of attention!'
[INFO] [1497368045.006407]: getting one image...
[INFO] [1497368045.120146]: got 3932160 bytes of image data
[INFO] [1497368046.238554]: Faces: []
[INFO] [1497368046.239918]: 'You are all looking great today!            Keep looking in my camera!'
[INFO] [1497368047.682537]: getting one image...
[INFO] [1497368047.746183]: got 3932160 bytes of image data
[INFO] [1497368048.908287]: Faces: [RecognizedFace(roi=(685, 530, 89, 102), l2_distances=[])]
[INFO] [1497368048.911917]: Calling Skybiometry...
[INFO] [1497368052.266168]: face_properties:
 - gender: 0
age: 36
[INFO] [1497368052.266395]: 'There are 1 males and 0 females in the crowd'
[INFO] [1497368056.216308]: State machine transitioning 'DETECT_CROWD':'succeeded'-->'REQUEST_OPERATOR'
[INFO] [1497368056.216545]: 'Who wants to play riddles with me?'
[INFO] [1497368058.203196]: State machine transitioning 'REQUEST_OPERATOR':'spoken'-->'WAIT_FOR_OPERATOR'
WaitForDesignator: waiting 0/3
[ERROR] [1497368058.214966]: No entities found in 

Designator(
  center_point = [           0,           0,           0] @ /map
  center_point_designator = None
  criteriafuncs = []
  debug = False
  ed = <robot_skills.world_model_ed.ED object at 0x7f22dde55c90>
  id = 
  id_designator = None
  lockable = <bound method EdEntityDesignator.lockable of Designator(resolve_type=<class 'robot_skills.util.entity.Entity'>, name=None)>
  name = None
  radius = 0
  resolve_type = <class 'robot_skills.util.entity.Entity'>
  robot = <robot_skills.amigo.Amigo object at 0x7f22de0926d0>
  type = human
  type_designator = None
  weight_function = <function <lambda> at 0x7f22ddab6500>)

WaitForDesignator: waiting 1/3
[ERROR] [1497368059.228135]: No entities found in 

Designator(
  center_point = [           0,           0,           0] @ /map
  center_point_designator = None
  criteriafuncs = []
  debug = False
  ed = <robot_skills.world_model_ed.ED object at 0x7f22dde55c90>
  id = 
  id_designator = None
  lockable = <bound method EdEntityDesignator.lockable of Designator(resolve_type=<class 'robot_skills.util.entity.Entity'>, name=None)>
  name = None
  radius = 0
  resolve_type = <class 'robot_skills.util.entity.Entity'>
  robot = <robot_skills.amigo.Amigo object at 0x7f22de0926d0>
  type = human
  type_designator = None
  weight_function = <function <lambda> at 0x7f22ddab6500>)

WaitForDesignator: waiting 2/3
[ERROR] [1497368060.242951]: No entities found in 

Designator(
  center_point = [           0,           0,           0] @ /map
  center_point_designator = None
  criteriafuncs = []
  debug = False
  ed = <robot_skills.world_model_ed.ED object at 0x7f22dde55c90>
  id = 
  id_designator = None
  lockable = <bound method EdEntityDesignator.lockable of Designator(resolve_type=<class 'robot_skills.util.entity.Entity'>, name=None)>
  name = None
  radius = 0
  resolve_type = <class 'robot_skills.util.entity.Entity'>
  robot = <robot_skills.amigo.Amigo object at 0x7f22de0926d0>
  type = human
  type_designator = None
  weight_function = <function <lambda> at 0x7f22ddab6500>)

[INFO] [1497368061.244254]: State machine transitioning 'WAIT_FOR_OPERATOR':'failed'-->'RIDDLE_GAME_1'
[INFO] [1497368061.244916]: Question: Question?, grammar: 
T[{actions : <A1>}] -> C[A1]

C[{A}] -> Q[A]

V_GUIDE -> guide | escort | ..
[INFO] [1497368061.252465]: Example: 'how many elders are in the crowd'
[ERROR] [1497368061.259268]: InvalidUserCodeError: Could not execute state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f22dda4ee50>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 180, in execute
    res = hear(self.robot, time_out=self.time_out)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 20, in hear
    return robot.hmi.query('Question?', knowledge.grammar, 'T', timeout=time_out)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 20, in query
    return self._client.query(description, grammar, target, timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 103, in query
    answer = self._wait_for_result_and_get(timeout=timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 58, in _wait_for_result_and_get
    execute_timeout = rospy.Duration(timeout) if timeout else rospy.Duration(10)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/rostime.py", line 90, in __init__
    super(Duration, self).__init__(secs, nsecs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/rostime.py", line 299, in __init__
    super(Duration, self).__init__(secs, nsecs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/rostime.py", line 73, in __init__
    secs = int(float_secs)
TypeError: int() argument must be a string or a number, not 'Duration'

[ERROR] [1497368061.259482]: Robot exited with <class 'smach.exceptions.InvalidUserCodeError'>,Could not execute state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f22dda4ee50>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 180, in execute
    res = hear(self.robot, time_out=self.time_out)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 20, in hear
    return robot.hmi.query('Question?', knowledge.grammar, 'T', timeout=time_out)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 20, in query
    return self._client.query(description, grammar, target, timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 103, in query
    answer = self._wait_for_result_and_get(timeout=timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 58, in _wait_for_result_and_get
    execute_timeout = rospy.Duration(timeout) if timeout else rospy.Duration(10)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/rostime.py", line 90, in __init__
    super(Duration, self).__init__(secs, nsecs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/rostime.py", line 299, in __init__
    super(Duration, self).__init__(secs, nsecs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/rostime.py", line 73, in __init__
    secs = int(float_secs)
TypeError: int() argument must be a string or a number, not 'Duration'
,<traceback object at 0x7f22dda650e0>
[INFO] [1497368061.259723]: Torso cancelling all goals on close
[INFO] [1497368061.259962]: left arm cancelling all goals on all arm-related ACs on close
[INFO] [1497368061.260448]: right arm cancelling all goals on all arm-related ACs on close
Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/challenge_spr/src/challenge_spr.py", line 207, in <module>
    startup(ChallengeSpeechPersonRecognition, challenge_name="challenge_spr")
  File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/util/startup.py", line 81, in startup
    outcome = executioner.execute()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
smach.exceptions.InvalidUserCodeError: Could not execute state 'RIDDLE_GAME_1' of type '<challenge_spr_states.riddle_game.HearQuestion object at 0x7f22dda4ee50>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 180, in execute
    res = hear(self.robot, time_out=self.time_out)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_spr/src/challenge_spr_states/riddle_game.py", line 20, in hear
    return robot.hmi.query('Question?', knowledge.grammar, 'T', timeout=time_out)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/api.py", line 20, in query
    return self._client.query(description, grammar, target, timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 103, in query
    answer = self._wait_for_result_and_get(timeout=timeout)
  File "/home/amigo/ros/kinetic/system/src/hmi/src/hmi/client.py", line 58, in _wait_for_result_and_get
    execute_timeout = rospy.Duration(timeout) if timeout else rospy.Duration(10)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/rostime.py", line 90, in __init__
    super(Duration, self).__init__(secs, nsecs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/rostime.py", line 299, in __init__
    super(Duration, self).__init__(secs, nsecs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/rostime.py", line 73, in __init__
    secs = int(float_secs)
TypeError: int() argument must be a string or a number, not 'Duration'

remote[amigo1-0]: bash: cannot set terminal process group (23529): Inappropriate ioctl for device
bash: no job control in this shell

[amigo1-0] killing on exit
[amigo1-0]: [amigo/robcup_recorder-10] killing on exit
[amigo1-0]: [amigo/record_relay_body_plan-7] killing on exit
[amigo1-0]: [amigo/record_throttle_base_laser-9] killing on exit
[amigo1-0]: [amigo/record_throttle_tf-3] killing on exit
[amigo1-0]: [amigo/record/audio_capture-2] killing on exit
[amigo1-0]: [amigo/record_throttle_ed_map-4] killing on exit
================================================================================REQUIRED process [state_machine-8] has died!
process has died [pid 18159, exit code 1, cmd /home/amigo/ros/kinetic/system/src/challenge_spr/src/challenge_spr.py amigo __name:=state_machine __log:=/home/amigo/.ros/log/f8cc9ea0-5049-11e7-ba3a-00031d0a0d6c/state_machine-8.log].
log file: /home/amigo/.ros/log/f8cc9ea0-5049-11e7-ba3a-00031d0a0d6c/state_machine-8*.log
Initiating shutdown!
================================================================================
[state_machine-8] killing on exit
[skybiometry_face_properties-7] killing on exit
[amigo/object_recognition/object_recognition-6] killing on exit
[amigo/face_recognition/face_recognition-5] killing on exit
[amigo/ed-3] killing on exit
[amigo/global_planner-2] killing on exit
[amigo/local_planner-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by MatthijsBurgh** [comment]
fixed by #319
