### ISSUE TITLE
TEST: GPSR commands

### ISSUE THREAD

**Issue by SamAlexandrov** [tue-robotics/tue_robocup#329]
> _Please tick only if it's tested on the robot and it's successfully done! The italic text is just a remark. 
All commands are applicable directly for Japan, so they could be tested even during the setup days!
For our environment please change some things like "manju" or "sink"._

Category I (Easy difficulty degree grammar):

   - [x] Tell me the name of the person in the kitchen [postponed]
   - [x] Get the noodles from the dining table and put it on the cupboard
   - [x] Navigate to the sink, locate the manju, and deliver it to me
   - [x] Give me the manju from the drawer
   - [x] Locate the drinks in the living room (_the drink is beer_)
   - [x] Pick up the peanuts from the bedside and bring it to me
   - [x] Grasp the soap from the cupboard and deliver it to me
   - [x] Tell me the name of the person in the office
   - [x] Find the soap in the kitchen
   - [x] Put the coke on the center table
   - [x] Locate a person in the bathroom and tell a joke
   - [x] Go to the bar, look for the noodles, and put it on the cupboard
   - [x] Find Alex in the living room and say what day is tomorrow
   - [x] Grasp the peanuts from the counter and deliver it to Skyler at the dining table
   - [x] Navigate to the dining table, find the beer, and put it on the TV stand
   - [x] Take the beer to the sink
   - [x] Tell me the name of the person in the bedroom
   - [x] Grasp the peanuts from the sink and place it on the dining table
   - [x] Find someone in the living room and say the time
   - [x] Navigate to the bedside, locate the tea, and place it on the counter
   - [x] Say a joke to Mia in the bedroom

Category II (Moderate difficulty degree grammar):

   - [x] Find the snacks in the bedroom
   - [x] Look for the paprika in the corridor
   - [ ] Go to the bed, meet Erika, and come after them _(Follow Erika to the corridor)_
   - [ ] Take Samuel from the sink to the cabinet _(The person being guided must deviate when indicated by the referee before reaching the cabinet)_
   - [ ] Tell me how many paprika there are on the center table
   - [ ] Go to the living shelf, locate the apple, and deliver it to Samantha at the cabinet
   - [ ] Locate a rising left arm person in the bedroom and answer a question _(Q: Which robot is used in the Domestic Standard Platform League;	A: The Toyota Human Support Robot)_
   - [ ] Pick up the apple from the bookcase and give it to Alex at the bed
   - [ ] Navigate to the cabinet, meet Charlie, and go after them _(Follow Charlie to the corridor)_
   - [ ] Tell me how many containers there are on the bar
   - [ ] Give me the mints from the dining table
   - [ ] Navigate to the bathroom, locate a female person, and say something about yourself
   - [ ] Look for a male person in the corridor and answer a question _(Q: Do you have dreams?; A: I dream of Electric Sheep.)_
   - [ ] Bring me the mints
   - [ ] Place the paprika on the cupboard
   - [ ] Tell me what's the thinnest snacks on the center table
   - [ ] Navigate to the desk, look for the apple, and deliver it to me
   - [ ] Tell me the name of the person in the office
   - [ ] Follow Erik from the cabinet to the bedroom
   - [ ] Give me the paprika

Category III (High difficulty degree grammar):

   - [ ] Robot please accompany Sophie from the dining table to the living table _(Sophie is not at the dining table but somewhere else in the same room)_
   - [ ] Could you please follow Thomas _(Thomas is at the cabinet)_
   - [ ] Robot please  Pour some cereals into the bowl
   - [ ] Bring me a containers _(the container is bowl)_
   - [ ] Robot please Tell me which are the three thinnest objects on the sink _(There are at least 5 objects on the sink)_
   - [ ] Please escort Brian to the living table _(Brian is at the sink)_
   - [ ] Could you please look for three food in the bathroom _(There will be only 3 objects in the room)_
   - [ ] Alex at the bed, go after her , and accompany her back _(Follow the person outside the arena)_
   - [ ] Give me the object under the tray from the bar _(There are at least 5 objects in the bar)_
   - [ ] Look for the bowl in the bathroom

**Comment by rokusottervanger** [comment]
Testing can be done as follows:
 - Start the simulator: 
```
amigo-start
```
 - Start the free mode, the --screen option lets the action server print output to the screen so that you can clearly see what's going on in case of an error:
```
amigo-free-mode --screen
```
 - Start the natural language console, the --debug makes sure that the semantics parsed from the sentence are printed to the screen:
```
robot-console --debug
```
 - The natural language console loads its grammar from the GPSR knowledge, so you can use this to pass tasks to the robot. Also you get tab completion (after the first word, at least, that can still be fixed, if you think it's important). If it doesn't complete (after the first word), it's not in the grammar:
```
[amigo] > get [tab]
[amigo] > get the [tab]
[amigo] > get the noodles [tab]
[amigo] > get the noodles from
...
```
until you get something like 
```
[amigo] > get the noodles from the cabinet and put them on the dinner_table
```
 - Check if the robot does what it is supposed to do. If it doesn't, fix it if you know what you're doing, otherwise ask me. If it does, throw a party, but not for too long, because there are probably other tasks that need to be fixed ;)

**Comment by LoyVanBeek** [comment]
Note: you can also pass a sentence directly to the robot_console:
```bash
robot-console --debug "get the noodles from the cabinet and put them on the dinner_table"
```

**Comment by rokusottervanger** [comment]
Although that doesn't give you tab completion ;)

**Comment by Rayman** [comment]
Command generator might change in the rulebook, let's close for now
