### ISSUE TITLE
Define for all locations where objects can be placed: in_front_of

### ISSUE THREAD

**Issue by egeerts** [tue-robotics/tue_robocup#33]

**Comment by rokusottervanger** [comment]
Have you finished this, @reinzor?

**Comment by reinzor** [comment]
Not all I guess but most yes. But there is a bug in the 'bed' object for
some reason.

-Rein

**Comment by egeerts** [comment]
bedbugs, always annoying xD

I'm wondering what the error is, guess we'll talk about it in an hour ;)

**Comment by reinzor** [comment]
I won't be there tonight unfortunately :/
