### ISSUE TITLE
GPSR: ask for confirmation before leaving the arena

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_robocup#339]
To make sure the robot does not leave the arena prematurely, first ask the operator to confirm that the challenge is done.

**Comment by MatthijsBurgh** [comment]
'Leave the arena' should be accepted by the action server, this way asking for confirmation is not needed.

**Comment by rokusottervanger** [comment]
We should reconsider issues like this once we have next year's rulebook. Closing it for now
