### ISSUE TITLE
SPR, unwanted rotation of the robot

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#341]

**Comment by LoyVanBeek** [comment]
When does this happen?

**Comment by MatthijsBurgh** [comment]
Rotates before answering; And I think it also rotates when it didn't hear anything

**Comment by Rayman** [comment]
It should rotate, that how you get points

**Comment by MatthijsBurgh** [comment]
But it should only rotate before answering. Not after/before other events, which is the case at the moment as I remember.

**Comment by SamAlexandrov** [comment]
Yesterday we tested that and it worked ok. You ask the question, it turns clockwise at 60 deg (I think :) ) and then answers. After applying the sound localization it should be changed to turn to the asking person.

**Comment by MatthijsBurgh** [comment]
Indeed fixed by SSL
