### ISSUE TITLE
Investigate (and switch to) Orbitty carrier board for TX2

### ISSUE THREAD

**Issue by Timple** [tue-robotics/tue_robocup#352]
Smaller footprint, cheaper, supports auto-boot

**Comment by hvrooy** [comment]
The manual is on http://connecttech.com/pdf/CTIM-ASG003_Manual.pdf 
Price is about USD 175 (see http://www.wdlsystems.com/Computer-on-Module/Orbitty/CTI-Orbitty-Carrier-for-NVIDIA-Jetson-TX1.html ) 
or about BP 170 (https://www.siliconhighwaydirect.co.uk/product-p/asg003.htm )

I will put it on the wish-list.....

**Comment by MatthijsBurgh** [comment]
I think these are excluding the TX2 itself. I don't think we can remove our TX2 from the dev board.
