### ISSUE TITLE
Autostart: absolute sensors in arms

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#377]
Arms fail to often after homing

**Comment by jlunenburg** [comment]
@MaxBaeten this has top prio IMHO, if it doesn't work no-one is able to start the robot...

**Comment by MaxBaeten** [comment]
In the arm there is screw thread. In this thread an insert is placed. This insert is loosened. locktite applied and fastened again so this issue should not occur anymore.
