### ISSUE TITLE
Autostart: bug hardware rebooten

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#378]
What causes the bug? Why does rebooting take so long?

**Comment by MaxBaeten** [comment]
I don't know what causes this bug but i can give a better description. When you start the hardware the spindle often goes into error. Can be overcome by restarting the hardware. If you start the hardware manually this never happens so it is related to autostart.

**Comment by MatthijsBurgh** [comment]
@MaxBaeten Solved by a sleep?

**Comment by MaxBaeten** [comment]
Yes possibly solved by a sleep of 5s before starting amigo-start service. But i will close the issue once we know for sure and decide on whether we keep this sleep or investigate something else.

**Comment by Rayman** [comment]
Solved for now, let's reopen if the issue persists
