### ISSUE TITLE
Action query server

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#381]
To notify the UI about the available actions, objects, etc.

**Comment by rokusottervanger** [comment]
Example: 
```
$ rosservice call /get_actions
actions: ['inspect', 'answer-question', 'arm-goal', 'gripper-goal', 'pick-up', 'say', 'guide', 'bring', 'look-at', 'place', 'reset-wm', 'follow', 'find', 'navigate-to']
```
The action-specific interface (a json dict) is not returned as of now. An alternative to returning all actions and their interfaces could be to add a service to provide the interface requested for a specific action.
