### ISSUE TITLE
Demo laptop

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#385]
* Dashboard
* Rviz
* UI
* Router

**Comment by MaxBaeten** [comment]
I didn't tape the router to the laptop since that resulted in a big mess. But i did take the BTO shoulder bag and put in everything you need to give a demo. Besides the emergency button. With this bag and the robot you should be able to give a demo. (We should add copies of a tutorial)

**Comment by MaxBaeten** [comment]
Still to do: 
- Test router 
- Cleanup laptop
- Make rviz shortcut/ demo config

**Comment by MatthijsBurgh** [comment]
Demo router, done

**Comment by MaxBaeten** [comment]
Reinstalled
Rviz shortcut added

ToDo:
Proper Offline Wiki
