### ISSUE TITLE
GPSR Demo

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#389]
Demo using speech

**Comment by rokusottervanger** [comment]
You can now start Amigo (demo mode is automatically started), launch the open challenge GUI and push the trigger button to enable GPSR mode. You can give simple single commands, including 'bring', 'grab', 'place', 'tell', but also 'present yourself', optionally prepended by 'amigo'. Not all actions are tested for their performance or user-friendliness, but I guess we can close this issue now.
