### ISSUE TITLE
How to threshold get_best_face_recognition()

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#399]
Many challenges want to threshold get_best_face_recognition(). But this is dependent on the dataset. Where do we store this, in the robocup knowledge?

**Comment by LoyVanBeek** [comment]
Seems reasonable, i wouldn't know a different place

**Comment by MatthijsBurgh** [comment]
For follow state, you could get a recognition after learning and use that probability*0.9.
