### ISSUE TITLE
Remove all dependencies on pein

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#4]
These packages still depend on pein.
## Focus
- [x] ~~robot_skills~~ fixed by tue-robotics/robot_skills#5?

## Challenges
- [x] challenge_basic_functionalities
- [x] challenge_demo
- [x] challenge_emergency
- [x] challenge_follow_me
- [x] challenge_restaurant

## Misc
- [x] ~~action_server~~ (only via robot_skills)
- [x] ~~amigo_demo~~
- [x] ~~human_tracking~~
- [x] ~~laser_ppl_detection~~
- [x] ~~perception_srvs~~
- [ ] ed_perception

**Comment by rokusottervanger** [comment]
Only ed_perception now depends on pein_srvs

**Comment by reinzor** [comment]
ed_perception does not depend on pein_srvs anymore
