### ISSUE TITLE
Robot was supposed to go into living room, but stopped at door

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#405]
@rokus @SamAlexandrov This was discovered in the test of 2017-09-05, you you remember any specifics, is there a log file perhaps?

**Comment by LarsJanssenTUe** [comment]
This behavior was seen in the test of today (2017-10-3) as well it was fixed by slightly altering the position of the robot (manually). After this it worked fine.

**Comment by LarsJanssenTUe** [comment]
The same problem is described somewhat more specific in https://github.com/tue-robotics/tue_robocup/issues/259, maybe close one of these issues?
