### ISSUE TITLE
[manipulation] Trying to get the room

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#43]

**Comment by LoyVanBeek** [comment]
Also, the ignore_... is implemented on an exclude list: 
   if not entity in exclude_list ...

But: Because there are new entities returned every time, the entity.__eq__ or == operator does not always work as the entities are not compared by value but by memory address by default if there is no __eq__ that takes the semantics of the object into account. 

We need to add a def __eq__(self, other): return self.id == other.id to EntityInfo-objects.

**Comment by Rayman** [comment]
```py
    def __eq__(self, other):
        ...
    def __ne__(self, other):
        ...
```
