### ISSUE TITLE
Spindle

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#446]
During homing, the spindle went up and hit the end or something and made a weird collision noise. Dashboard said homing was correct, but was not. I homed again. It was able to go up for a few cm's and went down to final position.

**Comment by hvrooy** [comment]
Strange behaviour. I am beginning to think the homing software is at fault here. There a two sensors that detect the upper and upper-upper limit, and both seem to be ignored somehow. Maybe they should  be more 'hard wired' in the safety circuit of the spindle motor. (I am not quite sure how to do that yet, though). To be continued.

**Comment by MatthijsBurgh** [comment]
@MaxBaeten you did some software fixes. Are these related to this issue?

**Comment by MaxBaeten** [comment]
No i did not change anything related to spindle homing. But i’ve never seen this issue myself

**Comment by MatthijsBurgh** [comment]
Ok, lets close it for now. I haven't seen it happen for more than a month.
