### ISSUE TITLE
[SPR/robot_skills] Implement openface and skybiometry in head

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#459]
Openface is already implemented. I don't know if the api in the SPR and robot_skills the same are. So check if this is usable and also implement skybiometry in robot_skills

**Comment by LoyVanBeek** [comment]
We used to have a 'perception' RobotPart fot this.
Putting perception stuff in Head, which also has a bunch of movement-related stuff seems weird

**Comment by MatthijsBurgh** [comment]
There is already a lot of it in there, so maybe you want to seperate it. But otherwise this is the way to go in my opinion.

**Comment by LoyVanBeek** [comment]
@jlunenburg opinions?

**Comment by Rayman** [comment]
Perception is good for me, then the head has only actuation in it.

**Comment by LoyVanBeek** [comment]
That would make sense to me as well. We also have SSL and HMI separated.

**Comment by jlunenburg** [comment]
Sounds sensible. Suppose you have a camera that is not mounted on the head.... 

Think about this there are more things that could be improved ;)
