### ISSUE TITLE
AMIGO Sound

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#466]
* Ping speaker (connected to Windows PC not working). N.B.: software has not been checked
* AMIGO speaker (connected to amigo1) did not sound loud enough (could not fix this using alsamixer)

**Comment by MatthijsBurgh** [comment]
Still an issue!

**Comment by hvrooy** [comment]
Intermittent errors are hard to find. I'd rather have it broken, so I can look for the error. 
I can't fix it if it ain't broke.....

**Comment by hvrooy** [comment]
Hartbeat-sound coming from both speakers has been fixed. Oxidation (bad contact) in the spring-loaded fuse holder between the contacts and the fuse caused the (intermittent) hart beat sound. Cleaning the contacts and reloading the spring in the fuse holder fixed it. (If  not, i will replace the current fuse holder with a better one.)

This did not fix the intermittent loss of PING _audio,_ though..............
