### ISSUE TITLE
Fail: bring me

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#468]
If 'bring me the pringles from the table' fails, it seems that no proper handover is done (the robot simply drops the object). We need to check what is desired though (navigation might fail in front of a furniture object)

**Comment by MatthijsBurgh** [comment]
This is done by https://github.com/tue-robotics/action_server/blob/master/action_server/src/action_server/actions/bring.py#L153. No other ways of opening the gripper are used.

**Comment by MatthijsBurgh** [comment]
Probably the detection is sensitive. Maybe the arm is stil a bit moving and therefore a handover is detected.
