### ISSUE TITLE
Add button: restart autostart service amigo2

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#474]
Backend ToDos
[ ] Create a launch file in robot_launch_files
[ ] Add a (std_msgs/String) publisher: what is the current launch file that is running
[ ] Add a parameter file in amigo_bringup: what are the launch files that can be launched, what is the default?
[ ] Update the node: launch the launch file as provided in the service

Frontend ToDos:
[ ] Add buttons to start, stop, restart
[ ] Display currently active launch file
[ ] Parse parameter file to list available launch files

**Comment by MatthijsBurgh** [comment]
Backend: @Timple 
GUI: @Rayman
