### ISSUE TITLE
Block the GUI buttons while the action server is running & implement cancel button

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#475]

**Comment by rokusottervanger** [comment]
Proposition: action server publishes its status on an action_server/status [action_server_msgs/status] topic on change (latched, so you can subscribe and still get the latest status).

action_server_msgs/status:
```
time stamp
string description
```
What should this description contain?

**Comment by LoyVanBeek** [comment]
- Which command are we processing
- What action is running

Can't this be a standard Diagnostics message?

**Comment by Rayman** [comment]
@rokusottervanger and me discussed this. There is an actionlib interface so the GUI already knows when it's busy and when it's finished. This has to be implement only on the GUI side.

**Comment by jlunenburg** [comment]
In general, functionality is missing in the current demo UI

**Comment by jlunenburg** [comment]
@rokusottervanger  When I call a cancel on the roslibjs actionclient, I can see the cancel message published over the `/amigo/action_server/task/cancel topic`.
