### ISSUE TITLE
answer question grammar missing in robotics_testlabs

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_robocup#482]
For the robotics_testlabs robot env, there is no "answer question grammar" available in the gpsr knowledge.

**Comment by MatthijsBurgh** [comment]
Why should there be an intermediate step to ask 'to answer a question'? Why not ask that question directly?

**Comment by rokusottervanger** [comment]
Because in the (EE)GPSR, a task can be "Find the person in the living room
and answer a question". Which means that the question should not be
answered immediately, but an intermediate step is necessary.

2017-11-01 16:14 GMT+01:00 Matthijs van der Burgh <notifications@github.com>
:

**Comment by MatthijsBurgh** [comment]
I remembered myself, right after posting. So I already deleted my comment
