### ISSUE TITLE
Replace Deprecated states in RIPS

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/tue_robocup#486]
Using State in <class 'robot_smach_states.startup.WaitForDoorOpen'> is deprecated, use smach.State instead and implement execute(self, userdata) instead of run(self, ...)
Using State in <class 'robot_smach_states.startup.ForceDrive'> is deprecated, use smach.State instead and implement execute(self, userdata) instead of run(self, ...)
Using State in <class 'robot_smach_states.startup.GoToEntryPoint'> is deprecated, use smach.State instead and implement execute(self, userdata) instead of run(self, ...)

**Comment by MatthijsBurgh** [comment]
fixed by #463
