### ISSUE TITLE
Better 3d camera's

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#501]
Can we see shiny and translucent objects better?

Check that camera has good ROS drivers.

**Comment by fibonatic** [comment]
I did a quick search and found this article: https://link.springer.com/chapter/10.1007/978-3-319-13560-1_33
I only skimmed through it, but it seems to say that they where able to improve seeing shiny and transparent objects.

**Comment by LoyVanBeek** [comment]
Could be useful: https://roscon.ros.org/2017/presentations/ROSCon%202017%203D%20Vision%20Technology.pdf

**Comment by MatthijsBurgh** [comment]
Not doing this, because this would need removal of all rgbd.

**Comment by LoyVanBeek** [comment]
Agreed, but this makes the rgbd package a major blocker for (potential) progress, which is a big risk too with the Kinects getting less and less available. Replacing RGBD and the kinect should be a goal next year.

**Comment by MatthijsBurgh** [comment]
We have an Intel Realsense ZR300

**Comment by LoyVanBeek** [comment]
Huh, how did that happen?

**Comment by MatthijsBurgh** [comment]
@hvrooy buying one

**Comment by alberth** [comment]
Nah, early Christmas present :)
