### ISSUE TITLE
Gather test/validation data of objects in our own lab

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#507]
- Under varying light conditions
- In various poses
- At various positions

Can be done with the demo tablet UI and commanding 'inspect the bookcase' etc.

**Comment by JosjaG** [comment]
Data retrieved on 14-11, manually segmented with a large margin can be found in MEGA/data/robotics_testlabs/training_data_Josja/data_lab_large_margin.
