### ISSUE TITLE
Check influence of margin around segmented object

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#509]
As an easy fix for bad segmentation: does classification improve when the image is not cropped strictly around the object's edges as reported by ED, but take some margin around that.

This can be tested for feasibility manually first. E.g. take a large margin around the object and automatically crop off e.g. 5%, 10%, 15& etc with something like image-magick (First copy the annotaed dir , then ```find . -name '*.jpg' -execdir mogrify -crop 90%x+0+0 -gravity Center {} \;```)

**Comment by alberth** [comment]
Random idea, what if you enlarge the image by copying the edge pixels repeatedly?
Would only work if there are no object pixels there, though

**Comment by LoyVanBeek** [comment]
In that case, there is no information added or removed. 

Segmentation should take care of taking only the data/pixels relevant for the object itself and not the context. A margin adds context and the intuition is that that is bad because we want to correctly recognize objects regardless of context (ie. recognize them in the bookcase just as well as the training on only the dinner table, for example).

In training, there should be no context, ideally, because we do not want the classifier to learn an association between the object and it's background.

**Comment by LoyVanBeek** [comment]
Results with the images from MEGA/data/robotics_testlabs/training_data_Josja/data_lab_large_margin, model is MEGA/data/robotics_testlabs/training_data_Josja/models_14/output_graph.pb

The best classifications seems to be in the 85-75% crop range. 

### 100%  crop, i.e. original images

![100pct_crop_result](https://user-images.githubusercontent.com/709259/33240526-566fdac8-d2b7-11e7-928c-48a403b69448.png)

### 95% crop
![95pct_crop_result](https://user-images.githubusercontent.com/709259/33240465-8c762f9c-d2b6-11e7-9ba4-be1b439ac97a.png)

### 90% crop
![90pct_crop_result](https://user-images.githubusercontent.com/709259/33240466-8c8f2a92-d2b6-11e7-9445-cf7eb1d08c9c.png)

### 85% crop
![85pct_crop_result](https://user-images.githubusercontent.com/709259/33240467-8ca59034-d2b6-11e7-9d5a-326e2f13c044.png)

### 80% crop
![80pct_crop_result](https://user-images.githubusercontent.com/709259/33240468-8cc14c52-d2b6-11e7-8136-bcad964af45b.png)

### 75% crop
![75pct_crop_result](https://user-images.githubusercontent.com/709259/33240469-8ce60420-d2b6-11e7-9cd7-7b27c4e9be08.png)

### 70% crop
![70pct_crop_result](https://user-images.githubusercontent.com/709259/33240470-8cfc37e0-d2b6-11e7-8552-6590f0285a89.png)

### 65% crop
![65pct_crop_result](https://user-images.githubusercontent.com/709259/33240471-8d131528-d2b6-11e7-98c7-519c2743128f.png)

### 60% crop
![60pct_crop_result](https://user-images.githubusercontent.com/709259/33240472-8d2ad604-d2b6-11e7-9975-b02693e6d6c0.png)

### 55% crop
![55pct_crop_result](https://user-images.githubusercontent.com/709259/33240473-8d42cf16-d2b6-11e7-8dc5-c5cd3331da55.png)

### 50% crop
![50pct_crop_result](https://user-images.githubusercontent.com/709259/33240474-8d5a0280-d2b6-11e7-90ce-62fce40e7da8.png)

### 45% crop
![45pct_crop_result](https://user-images.githubusercontent.com/709259/33240475-8d7178b6-d2b6-11e7-8d5b-4e3167a6e756.png)

### 40% crop
![40pct_crop_result](https://user-images.githubusercontent.com/709259/33240476-8d956064-d2b6-11e7-8c1c-80016c824666.png)

**Comment by MatthijsBurgh** [comment]
What is defined as 100%? Which ratio is similar to the images of ED?

**Comment by LoyVanBeek** [comment]
100% is how @JosjaG  cropped the images manually. I'll upload some example pictures of what each crop looks like later. 

It seems however that how ED crops the images now is quite close to the optimum, but this is just my observation.

**Comment by LoyVanBeek** [comment]
100%
![2017-11-21-20-10-49_227552](https://user-images.githubusercontent.com/709259/33675828-2c199386-dab4-11e7-9f31-aea8202b5584.jpg)

90%
![2017-11-21-20-10-49_227552](https://user-images.githubusercontent.com/709259/33675851-4c39ba60-dab4-11e7-91f7-557cfbc0ecd9.jpg)

80%: More or less the optimum, so tightly cropped to the bounding box of the object itself. 
![2017-11-21-20-10-49_227552](https://user-images.githubusercontent.com/709259/33675866-56a68028-dab4-11e7-866b-8cac65d7e968.jpg)

70%
![2017-11-21-20-10-49_227552](https://user-images.githubusercontent.com/709259/33675883-5eb43c74-dab4-11e7-91ec-791edce95bec.jpg)

60%
![2017-11-21-20-10-49_227552](https://user-images.githubusercontent.com/709259/33675888-636aff1e-dab4-11e7-9cf2-00ddd4025333.jpg)

50%
![2017-11-21-20-10-49_227552](https://user-images.githubusercontent.com/709259/33675897-6c850b8a-dab4-11e7-9203-ab19542c22c3.jpg)

40%:
![2017-11-21-20-10-49_227552](https://user-images.githubusercontent.com/709259/33675821-249df85e-dab4-11e7-83fa-4e1e4ab24003.jpg)

**Comment by LoyVanBeek** [comment]
Next up: check how ED currently does segmentation and adjust the margin it uses to the optimum we found.
