### ISSUE TITLE
Compare the accuracy of a classifier when trained on N classes.

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#510]
Does the accuracy diminish with increasing N classes and how much?

**Comment by JosjaG** [comment]
Different sets trained on 3, 6, 9, 12 and 15 of the classes from /home/amigo/MEGA/data/robotics_testlabs/training_data_Josja/training:
3 classes:
![figure_1](https://user-images.githubusercontent.com/29233213/33795089-54916de8-dcda-11e7-95af-f30d5728c8fd.png)
6 classes:
![figure_1](https://user-images.githubusercontent.com/29233213/33795092-5bcdb90e-dcda-11e7-891f-bdc66d236683.png)
9 classes:
![figure_1](https://user-images.githubusercontent.com/29233213/33795093-636cfcce-dcda-11e7-8ca6-18e9b2212c77.png)
12 classes:
![figure_1](https://user-images.githubusercontent.com/29233213/33795094-6af6af76-dcda-11e7-98d3-651dc1d065d3.png)
15 classes:
![figure_1](https://user-images.githubusercontent.com/29233213/33795103-877ce534-dcda-11e7-9e63-721d2742c039.png)
Increasing the number of classes does lead to a decrease in the accuracy, as expected. This means that it might be a good idea to limit the number of classes if we don't have a lot of data.

**Comment by MatthijsBurgh** [comment]
Conclusion: Reduce number of classes. So remove classes, which can't be detected. (Maybe also the classes that are always classified wrong/always have a too low probability.)
