### ISSUE TITLE
Buy spare Kinects

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#512]
Check very very well that it's the right model

**Comment by hvrooy** [comment]
Bought a used kinect type 1414 via 'UsedProducts'. I am waiting for the package to arrive.

**Comment by hvrooy** [comment]
One second hand Kinect 1414 has arrived. Testing the goods tomorrow......(DevDay)

**Comment by hvrooy** [comment]
Kinect 1414 turned out to be fully functional, so we have one extra spare. Kinect is labeled ' 'Kinect 1414 _ spare 20171209'  ans is located in the usual box.
