### ISSUE TITLE
Play in bearing support of head

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#520]
One bolt doesn't get catch anymore. Maybe the nut moved.

**Comment by hvrooy** [comment]
I already noticed that, but Gerard was not available yet. I will see to the repair ASAP. I guess the insert came loose and may have to be replaced with something better.

**Comment by hvrooy** [comment]
Gerard is aware of the issue, and will fix it asap.

**Comment by MatthijsBurgh** [comment]
As discussed with @hvrooy, Gerard will fix it this month. It will not overlap with our meetings.

**Comment by hvrooy** [comment]
Mounting of dynamixels is fixed. Head is secure again. One nut had disappeared. Lost nut was not recovered....... ;-(
