### ISSUE TITLE
navigation to unknown area

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/tue_robocup#530]
restaurant challenge starts with gmapping and makes a map on the go. It should be able to navigate to and trough unknown areas which it currently does not.
I am quite sure that it did last robocup.

**Comment by MaxBaeten** [comment]
![restaurantchallenge_notdrivingunknownspace](https://user-images.githubusercontent.com/6431163/34174937-fef0dc10-e4fa-11e7-8323-feebd4a96d8f.png)

**Comment by MaxBaeten** [comment]
When Started like the picture above, with gmapping you can only map the square. Amigo will not drive to (the person waving, the dark red lines on the top right).

**Comment by MatthijsBurgh** [comment]
This is allowed at the moment, so outdated.
