### ISSUE TITLE
use phrase generator from robocup to autotest GPSR

### ISSUE THREAD

**Issue by timassman** [tue-robotics/tue_robocup#534]
The phrase generator used at RoboCup is made available by the committee. We can use this to automate testing and gather statistics which kind of commands we need to work on.

**Comment by timassman** [comment]
A generator is publicly available at https://github.com/kyordhel/GPSRCmdGen

**Comment by timassman** [comment]
Pull request: https://github.com/tue-robotics/tue-env/pull/220

**Comment by LoyVanBeek** [comment]
With tue-robotics/tue-env#220 merged, can we close this @timassman ?
