### ISSUE TITLE
Amigo picks up the same item with both its hands

### ISSUE THREAD

**Issue by fibonatic** [tue-robotics/tue_robocup#552]
When running the storing groceries challenge in the simulator Amigo always picks up the same item with both its right and left hand from the table.

**Comment by MatthijsBurgh** [comment]
Could you explain your actions and how to reproduce?

**Comment by fibonatic** [comment]
In order to reproduce run the storing groceries challenge in the simulator (so "rosrun challenge_storing_groceries add_entities.py" and "amigo-challenge-storing-groceries"). After inspecting the bookcase amigo drivers to the dinner table, on which three items are spawned. Amigo then always grasps the right most item with both its right and left hand (it also has to same item id).
