### ISSUE TITLE
Amigo Button in open_challenge GUI not working (or long delay) in demo

### ISSUE THREAD

**Issue by bobhendrikx** [tue-robotics/tue_robocup#561]
During and before demonstration Amigo is often not responding to the AMIGO button (to listen to operator)
Multiple restarts did not resolve the issue. 
Sometimes it does respond but takes more than a minute, and sometimes it responds instantly

**Comment by MatthijsBurgh** [comment]
It is not the gui, but the state_machine. Because msgs are published on the topic. Double issue, already there #524
