### ISSUE TITLE
Jetson TX2 SERGIO

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#576]
Deliverable:
- [ ] Working OpenPose on SERGIO. Skeletons should be good visualized in rviz.

Steps:
- [ ] Mount Jetson on CarrierBoard, including all other hardware connections
- [ ] Install/Update OS
- [ ] Install Jetson libraries
- [ ] Install OpenPose
- [ ] Place in SERGIO
- [ ] Test

**Comment by Timple** [comment]
Simple dd from amigo-jetson to sergio-jetson was no success :(

Next step: clean install.

**Comment by LoyVanBeek** [comment]
Is https://github.com/rbonghi/jetson_easy helpful?
