### ISSUE TITLE
Chrony does not sync Amigo1 and Amigo2 properly

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_robocup#579]
After a restart of the chrony service on amigo2, they sync again. But on startup they don't.

**Comment by Timple** [comment]
The problem with these intermittent issues is that they are hard to debug.

@rokusottervanger 
- Did this occur once or more often?
- How did you notice the problem?

**Comment by rokusottervanger** [comment]
- As I understand, this happened consistently in the last few days. 
 - A graduation student was trying to get his own executive working, but was testing the demo mode first. He could not get Kinect images until after a restart of the chrony service on amigo2 (clocks were out of sync by a few minutes).
 - This happened last friday morning and last monday morning at least.

**Comment by Timple** [comment]
Good do know it reproduces kind of. Might we get the output of `chronyc tracking` of both amigos next time this occurs? Before restarting anything obviously.

**Comment by LoyVanBeek** [comment]
We had a similar problem on Sergio today. Solution was to allow sergio2's IP address in the chrony.conf of sergio1.

**Comment by MatthijsBurgh** [comment]
I have not been experiencing this issue. Rebooting AMIGO2 always solves the problem for me.
