### ISSUE TITLE
[Amigo] Free-mode bring coke from dinner tabe to bookcase, grasp failing (robot-console)

### ISSUE THREAD

**Issue by bobhendrikx** [tue-robotics/tue_robocup#584]
Error during grasping through the robot-console:

[ERROR] [1524049954.353489]: SimpleActionClient received DONE twice
[ERROR] [1524050143.441809]: InvalidUserCodeError: Could not execute state 'GRAB' of type '<robot_smach_states.manipulation.grab.PickUp object at 0x7fdf63cce410>': Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/manipulation/grab.py", line 154, in execute
    if self.robot.tf_listener.waitForTransform("/map", self.robot.robot_name + "/base_link"):
TypeError: waitForTransform() takes at least 5 arguments (3 given)

[ERROR] [1524050143.442393]: Action execution crashed, requesting preempt of action sequence
[ERROR] [1524050143.443964]: Exception in your execute callback: An error occurred using task recipe: {'actions': [{'action': 'bring', 'source-location': {'id': 'dinner_table'}, 'object': {'type': 'coke'}, 'target-location': {'id': 'bookcase'}}]}
Implement me in Bring.
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/action_server.git/action_server/src/action_server/server.py", line 91, in _add_action_cb
    raise type(e)("An error occurred using task recipe: %s\n" % goal.recipe + e.message)
NotImplementedError: An error occurred using task recipe: {'actions': [{'action': 'bring', 'source-location': {'id': 'dinner_table'}, 'object': {'type': 'coke'}, 'target-location': {'id': 'bookcase'}}]}
Implement me in Bring.

**Comment by LoyVanBeek** [comment]
@MatthijsBurgh This seems quire related to #582 etc.

**Comment by bobhendrikx** [comment]
Issue appears to be gone in master, i should have checked that first  :o)

**Comment by MatthijsBurgh** [comment]
Yep, this issue is fixed by #582. So updated master is the solution. #582 should be merged in all branches using tf listener instead of tf_server.
