### ISSUE TITLE
Add more questions and answers

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#597]
- Which one is the bigger object?
- Crowd questions?

**Comment by SamAlexandrov** [comment]
Crowd questions:
- gesture recognition;
- the colour of the clothes.

Object questions:
- bigger / smaller - implemented, testing in process
- lighter / heavier

Multiple objects - make difference between "bed" and "beds" - grammar enchancement :)

**Comment by SamAlexandrov** [comment]
#610 deals with all enhancements and updates for SPR.
It will be merged after #590 :)
