### ISSUE TITLE
Move head while waiting for a waving person

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#600]
See how to implement this: maybe wait for a while before moving the head. Definitely make it optional so that it's easy to change

**Comment by MatthijsBurgh** [comment]
@Rayman continued on this on the `robocup` branch of RWC2018. This issue can be closed after `robocup` is merged into the master.

**Comment by LoyVanBeek** [comment]
Would it make sense to use Sound-source localization for this as well? Just have some simple node to look in the direction of the SSL vector using head_ref?

**Comment by MatthijsBurgh** [comment]
#639 is merged, so closing.
