### ISSUE TITLE
Improve visualization

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#602]
In Magdeburg, the Final challenge looked too 'scripted': it might have been hardcoded that Lars was at the door and where Josja was in the bedroom. This has to be visualized properly and be incorporated in the flow of the demo

**Comment by LoyVanBeek** [comment]
Additional ideas were: 

- Bounding boxes around detections in the image that we send back to Telegram/Slack
- Asking the jury who to put at the door or even have a jury member go to the door and other places where a detection needs to happen
