### ISSUE TITLE
SERGIO 5GHz WiFi antenna

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#611]
Last week, bad 5GHz WiFi reception caused SERGIO not to work on the RoboCup network. Therefore, we've switched to a 2.4 GHz network. At RoboCup in Montreal, it might be wise to support both networks (2.4 usually is awfully crowded). It seems that one or more of the 5 GHz antennas are missing (there's one near the power supplies). I don't know who/how this got broken, but could it be fixed?

**Comment by hvrooy** [comment]
I noticed one broken antenna,  but  there does not seem to be a place to attach it. We ave 5 antennas, but i could only find 4 places to attach one. (Antenna should be in the lab...)
Will look harder......

**Comment by Timple** [comment]
5GHz is an official requirement even I think. There is no 2.4 support officially except for the peppers I believe.

**Comment by hvrooy** [comment]
The broken antenna is fixed and reconnected to the router. However, quick testing was not possible by just switching the robot on. Conclusion: hardware probably OK now, but a final test has still to be done.

**Comment by jlunenburg** [comment]
Mooi, kunnen we dat zaterdag testen (of indien eerder gewenst: log in op de
router (192.168.44.70), zet 5 GHz antenne aan en verbind met ROPOD netwerk
(neem aan dat dit ook 5 GHz ondersteunt))

Op do 31 mei 2018 12:17 schreef TheToolman <notifications@github.com>:

**Comment by MatthijsBurgh** [comment]
Easy to check with Wi-Fi analyser
