### ISSUE TITLE
RWC 2018 aftermath

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#620]
Please help with the clean-up.
`rwc2018` branch needs to be deleted at all times. PR for `robocup` branch when ahead, otherwise delete it

EDIT: All `rwc2018` branches have been deleted, only PRs need to be created, reviewed etc.

- [ ] [action_server](https://github.com/tue-robotics/action_server)  rwc2018 branch deleted, [PR](https://github.com/tue-robotics/action_server/pull/101) is open
- [ ] [amigo_bringup](https://github.com/tue-robotics/amigo_bringup) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/amigo_bringup/pull/99) is open
- [X] [amigo_description](https://github.com/tue-robotics/amigo_description) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/amigo_description/pull/20) is merged.
- [x] [amigo_hardware](https://github.com/tue-robotics/amigo_hardware) No changes.
- [x] [amigo_moveit_config](https://github.com/tue-robotics/amigo_moveit_config) No changes.
- [x] [amigo_msgs](https://github.com/tue-robotics/amigo_msgs) No changes.
- [x] [amigo_ref_interpolator](https://github.com/tue-robotics/amigo_ref_interpolator) No changes.
- [x] [ar_marker_detector](https://github.com/tue-robotics/ar_marker_detector) No changes.
- [x] [audio_common](https://github.com/tue-robotics/audio_common) No changes.
- [x] [battery_manager](https://github.com/tue-robotics/battery_manager) No changes.
- [x] [cb_base_navigation](https://github.com/tue-robotics/cb_base_navigation) No changes.
- [x] [cb_planner_msgs_srvs](https://github.com/tue-robotics/cb_planner_msgs_srvs) No changes.
- [x] [code_profiler](https://github.com/tue-robotics/code_profiler) No changes.
- [x] [control_msgs](https://github.com/tue-robotics/control_msgs) No changes.
- [x] [conversation_engine](https://github.com/tue-robotics/conversation_engine) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/conversation_engine/pull/15) is merged
- [x] [dashboard](https://github.com/tue-robotics/dashboard) No changes.
- [x] [diagnostics](https://github.com/tue-robotics/diagnostics) No changes.
- [x] [dialogflow_ros](https://github.com/tue-robotics/dialogflow_ros) No changes.
- [x] [dragonfly_speech_recognition](https://github.com/tue-robotics/dragonfly_speech_recognition) PR already performed during RWC2018
- [x] [dynamixel_jointstate_conversion](https://github.com/tue-robotics/dynamixel_jointstate_conversion) No changes.
- [x] [dynamixel_motor](https://github.com/tue-robotics/dynamixel_motor) No changes.
- [x] [dynamixel_ros_control](https://github.com/tue-robotics/dynamixel_ros_control) No changes.
- [x] [ed](https://github.com/tue-robotics/ed) No changes.
- [x] [ed_gui_server](https://github.com/tue-robotics/ed_gui_server) No changes.
- [x] [ed_localization](https://github.com/tue-robotics/ed_localization) No changes.
- [x] [ed_moveit](https://github.com/tue-robotics/ed_moveit) No changes.
- [x] [ed_msgs](https://github.com/tue-robotics/ed_msgs) No changes.
- [x] [ed_navigation](https://github.com/tue-robotics/ed_navigation) No changes.
- [x] [ed_object_models](https://github.com/tue-robotics/ed_object_models) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/ed_object_models/pull/23) merged
- [x] [ed_perception](https://github.com/tue-robotics/ed_perception) No changes.
- [x] [ed_perception_models](https://github.com/tue-robotics/ed_perception_models) No changes.
- [x] [ed_robocup](https://github.com/tue-robotics/ed_robocup) No changes.
- [x] [ed_rviz_plugins](https://github.com/tue-robotics/ed_rviz_plugins) No changes.
- [x] [ed_sensor_integration](https://github.com/tue-robotics/ed_sensor_integration) No changes.
- [x] [ed_tutorials](https://github.com/tue-robotics/ed_tutorials) No changes.
- [x] [ed_wire](https://github.com/tue-robotics/ed_wire) No changes.
- [x] [emc-env](https://github.com/tue-robotics/emc-env) No changes.
- [x] [emc_simulator](https://github.com/tue-robotics/emc_simulator) No changes.
- [x] [emc_system](https://github.com/tue-robotics/emc_system) No changes.
- [x] [emergency_speakup](https://github.com/tue-robotics/emergency_speakup) No changes.
- [x] [ethercat_interface](https://github.com/tue-robotics/ethercat_interface) No changes.
- [x] [executive_smach](https://github.com/tue-robotics/executive_smach) No changes.
- [x] [fast_simulator](https://github.com/tue-robotics/fast_simulator) No changes.
- [X] [fast_simulator_data](https://github.com/tue-robotics/fast_simulator_data) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/fast_simulator_data/pull/6) is merged.
- [x] [geolib2](https://github.com/tue-robotics/geolib2) No changes.
- [x] [gitim](https://github.com/tue-robotics/gitim) No changes.
- [x] [gpsr_command_generator](https://github.com/tue-robotics/gpsr_command_generator) No changes.
- [x] [GPSRCmdGen](https://github.com/tue-robotics/GPSRCmdGen) No changes on our side. Update to latest version of Mauricio.
- [x] [grammar_parser](https://github.com/tue-robotics/grammar_parser) No changes.
- [x] [gripper_detector](https://github.com/tue-robotics/gripper_detector) No changes.
- [x] [head_ref](https://github.com/tue-robotics/head_ref) No changes.
- [x] [head_ref_ed_client](https://github.com/tue-robotics/head_ref_ed_client) No changes.
- [x] [hmi](https://github.com/tue-robotics/hmi) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/hmi/pull/16) is merged
- [x] [image_recognition](https://github.com/tue-robotics/image_recognition) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/image_recognition/pull/62) is merged
- [x] [image_recognition-release](https://github.com/tue-robotics/image_recognition-release) No changes.
- [x] [image_recognition_wire](https://github.com/tue-robotics/image_recognition_wire) No changes.
- [x] [kinect_driver](https://github.com/tue-robotics/kinect_driver) No changes.
- [x] [matrix_creator_ros](https://github.com/tue-robotics/matrix_creator_ros) No changes.
- [x] [multirobot_communication](https://github.com/tue-robotics/multirobot_communication) No changes.
- [x] [navigation](https://github.com/tue-robotics/navigation) No changes.
- [x] [nl_robot_console](https://github.com/tue-robotics/nl_robot_console) No changes.
- [x] [node_alive](https://github.com/tue-robotics/node_alive) No changes.
- [x] [openpose](https://github.com/tue-robotics/openpose) No changes.
- [x] [people_detector](https://github.com/tue-robotics/people_detector) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/people_detector/pull/6) is merged
- [x] [picaso_4d_systems](https://github.com/tue-robotics/picaso_4d_systems) No changes.
- [x] [pico_base_controller](https://github.com/tue-robotics/pico_base_controller) No changes.
- [x] [pico_bringup](https://github.com/tue-robotics/pico_bringup) No changes.
- [x] [pico_talk](https://github.com/tue-robotics/pico_talk) No changes.
- [x] [qr_detector_zbar](https://github.com/tue-robotics/qr_detector_zbar) No changes.
- [x] [r5cop_demo](https://github.com/tue-robotics/r5cop_demo) No changes.
- [x] [rgb_lights_manager](https://github.com/tue-robotics/rgb_lights_manager) No changes.
- [x] [rgbd](https://github.com/tue-robotics/rgbd) No changes.
- [x] [robot-api](https://github.com/tue-robotics/robot-api) No changes.
- [x] [robot_launch_files](https://github.com/tue-robotics/robot_launch_files) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/robot_launch_files/pull/31) is merged
- [x] [ros_controllers](https://github.com/tue-robotics/ros_controllers) No changes.
- [x] [rosbridge_suite](https://github.com/tue-robotics/rosbridge_suite) No changes.
- [x] [rosdistro](https://github.com/tue-robotics/rosdistro) No changes.
- [x] [rtt](https://github.com/tue-robotics/rtt) No changes.
- [x] [rtt_control_components](https://github.com/tue-robotics/rtt_control_components) No changes.
- [x] [rtt_soem](https://github.com/tue-robotics/rtt_soem) No changes.
- [x] [rtt_tue_msgs](https://github.com/tue-robotics/rtt_tue_msgs) No changes.
- [x] [rwc2016_data](https://github.com/tue-robotics/rwc2016_data) No changes.
- [x] [scl_filters](https://github.com/tue-robotics/scl_filters) No changes.
- [ ] [sergio_bringup](https://github.com/tue-robotics/sergio_bringup) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/sergio_bringup/pull/19) is open
- [x] [sergio_control](https://github.com/tue-robotics/sergio_control) No changes.
- [x] [sergio_description](https://github.com/tue-robotics/sergio_description)No changes.
- [x] [sergio_gripper_moveit_config](https://github.com/tue-robotics/sergio_gripper_moveit_config) No changes.
- [x] [sergio_hardware](https://github.com/tue-robotics/sergio_hardware) No changes.
- [x] [sergio_moveit_config](https://github.com/tue-robotics/sergio_moveit_config) No changes.
- [x] [sergio_torso_calibration](https://github.com/tue-robotics/sergio_torso_calibration) No changes.
- [x] [simulink_models](https://github.com/tue-robotics/simulink_models) No changes.
- [x] [slack_ros](https://github.com/tue-robotics/slack_ros) No changes.
- [x] [snowboy_ros](https://github.com/tue-robotics/snowboy_ros) No changes.
- [x] [soem](https://github.com/tue-robotics/soem) No changes.
- [x] [speech_recognition](https://github.com/tue-robotics/speech_recognition) No changes.
- [x] [telegram_ros](https://github.com/tue-robotics/telegram_ros) No changes.
- [x] [teleop_twist_web](https://github.com/tue-robotics/teleop_twist_web) No changes.
- [x] [tensorflow_playground](https://github.com/tue-robotics/tensorflow_playground) No changes.
- [x] [text_to_speech](https://github.com/tue-robotics/text_to_speech) No changes.
- [x] [tf_checker](https://github.com/tue-robotics/tf_checker) No changes.
- [x] [tf_server](https://github.com/tue-robotics/tf_server) No changes.
- [x] [tue-env](https://github.com/tue-robotics/tue-env) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/tue-env/pull/272) is merged
- [x] [tue-robotics.github.io](https://github.com/tue-robotics/tue-robotics.github.io) No changes.
- [x] [tue_config](https://github.com/tue-robotics/tue_config) No changes.
- [x] [tue_control](https://github.com/tue-robotics/tue_control) No changes.
- [x] [tue_control_rtt](https://github.com/tue-robotics/tue_control_rtt) No changes.
- [x] [tue_control_rtt_msgs](https://github.com/tue-robotics/tue_control_rtt_msgs) No changes.
- [x] [tue_control_tools](https://github.com/tue-robotics/tue_control_tools) No changes.
- [x] [tue_docs](https://github.com/tue-robotics/tue_docs) No changes.
- [x] [tue_ethercat_drivers](https://github.com/tue-robotics/tue_ethercat_drivers) No changes.
- [x] [tue_filesystem](https://github.com/tue-robotics/tue_filesystem) No changes.
- [x] [tue_hsr](https://github.com/tue-robotics/tue_hsr) No changes.
- [x] [tue_manipulation](https://github.com/tue-robotics/tue_manipulation) No changes.
- [x] [tue_manipulation_msgs](https://github.com/tue-robotics/tue_manipulation_msgs) No changes.
- [x] [tue_mobile_ui](https://github.com/tue-robotics/tue_mobile_ui) rwc2018 branch deleted, [PR](https://github.com/tue-robotics/tue_mobile_ui/pull/32) is merged
- [x] [tue_msgs](https://github.com/tue-robotics/tue_msgs) No changes.
- [x] [tue_robocup](https://github.com/tue-robotics/tue_robocup) All PRs merged, rwc2018 branch deleted
- [x] [tue_serialization](https://github.com/tue-robotics/tue_serialization) No changes.
- [x] [tue_simulink_ethercat](https://github.com/tue-robotics/tue_simulink_ethercat) No changes.
- [x] [tue_teleop_keyboard](https://github.com/tue-robotics/tue_teleop_keyboard) No changes.
- [x] [virtual_cam](https://github.com/tue-robotics/virtual_cam) No changes.
- [x] [wire](https://github.com/tue-robotics/wire) No changes.

**Comment by MatthijsBurgh** [comment]
Lets move the following repos to the graveyard:
- [ ] [gpsr_command_generator](https://github.com/tue-robotics/gpsr_command_generator)
- [ ] [picaso_4d_systems](https://github.com/tue-robotics/picaso_4d_systems)
- [ ] [rwc2016_data](https://github.com/tue-robotics/rwc2016_data)
- [ ] [tf_checker](https://github.com/tue-robotics/tf_checker)
- [ ] [tue_control_rtt](https://github.com/tue-robotics/tue_control_rtt)
- [ ] [tue_control_rtt_msgs](https://github.com/tue-robotics/tue_control_rtt_msgs)
- [ ] [tue_control_tools](https://github.com/tue-robotics/tue_control_tools)

**Comment by LoyVanBeek** [comment]
Allrighty, branches have been split up. Each challenge has a PR: rwc2018/<challenge_name>2 (the 2 because I forgot to include the relevant knowledge file originally"

@tue-robotics all: please create a PR from the branch you worked on, so others can review and approve of your work. 

The script I used to split the branches is at https://gist.github.com/LoyVanBeek/06cc66d8d3101ce539bf5264e2f2674b
