### ISSUE TITLE
Grasp offset is hardcoded in robot.py

### ISSUE THREAD

**Issue by JosjaG** [tue-robotics/tue_robocup#626]
The grasp offset is hardcoded in robot.py, which causes a problem for the implementation on Hero. 
https://github.com/tue-robotics/tue_robocup/blob/189bd987822f9bd1c477769892e154964f97d2f0/robot_skills/src/robot_skills/robot.py#L85
A simple fix would be to overwrite the variable in hero.py, but it would be much cleaner is the parameter was simply loaded from the robot description.

**Comment by MatthijsBurgh** [comment]
PR merged
