### ISSUE TITLE
HERO video material

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#655]
- [x] Please list all video material you have available.
- [x] Please list video material which we have of AMIGO, but not from HERO, and which could be filmed next Tuesday.

**Comment by JosjaG** [comment]
In the lab:
- Navigation (combination of rviz and regular video)
- Picking up and placing objects
- Inspecting (rviz)
- ED web GUI (interactive map building) (combination of rviz and screen video)
- Telegram + hand over

In Arnhem (we have to check if we can use this):
- Navigation
- Picking up and handing over
- Picking up and placing
- Finding person in room

**Comment by JosjaG** [comment]
What the AMIGO qualification video has that we don't:
- Video of rviz and simultaneously 
- Long videos (but that is probably a good thing :p)
- Imitation learning
- Separate object recognition (you do see it with the inspect, but that's not very clear)
- Robot-console (but we do show Telegram so I don't know if we need that)
- Small object detection
- Person/Face recognition
- Pose detection

**Comment by JosjaG** [comment]
We could film:
- More live with simultaneous rviz video's
- Separate object and face recognition
- Small object detection

**Comment by MatthijsBurgh** [comment]
Good busy!

**Comment by JosjaG** [comment]
We made all the video's today, and I'll try to edit everything on Friday. I hope to have a draft finished by the end of the weekend!
