### ISSUE TITLE
remove hardcoded left and right arms in robot_skills and challenges

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#672]

**Comment by MatthijsBurgh** [comment]
Is suggest a deadline of end of January. Is this possible?

**Comment by alberth** [comment]
That sounds quite doable wrt code changes for the challenges at least; deeper down (`robot.py`) still has them, as well as ROS topics by that name, which originate from somewhere unknown to me and go to other code also unknown to me.

The other exception is in robot test files but those are robot-specific so seems fine to me.
