### ISSUE TITLE
Challenge manipulation: Update empty spot designator

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_robocup#71]
Designator returns empty spots that are not able to be placed on

**Comment by reinzor** [comment]
Is this covered @jlunenburg ?

**Comment by LoyVanBeek** [comment]
One solution could be to take distance to center of 'in_front_of' area of the place_location-designator into account. 
You can get that via 

```python
ds.EntityByIdDesignator(amigo, id='bookcase').resolve().data['areas']
``` in the amigo-console

**Comment by LoyVanBeek** [comment]
Addressed in https://github.com/tue-robotics/robot_smach_states/pull/57
