### ISSUE TITLE
Chrony failed on Hero backpack laptop

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue_robocup#725]
Chrony fails on `hero2`. (Also on `athome11`)

Probably caused by not automatically connecting network. (#731)

Written by @PetervDooren  about `athome11`
1. Running `chronyc tracking` reported that the daemon could not be contacted. 
2. `systemctl status chrony` reports that it could not parse an `allow` line in its config. This line is `allow hero1.local`.
3. According to https://bugzilla.redhat.com/show_bug.cgi?id=1406445 a reason could be that the hostname was not resolvable. 
4. `systemctl restart chrony` fixed that, because by now the hostname can be resolved. 
 Potential final fix: Make `chrony.service` depend on `networking.target` in systemd?

**Comment by MatthijsBurgh** [comment]
Still an issue on `HERO2`?

**Comment by LoyVanBeek** [comment]
Not AFAIK (I wrote this issue with @PetervDooren). We put this on GitHub for future reference essentially.

**Comment by PetervDooren** [comment]
We encountered this problem on athome11. Unless chrony.service works differently on hero2 I would expect to also see this there.

**Comment by MatthijsBurgh** [comment]
I have not experienced it myself.

**Comment by LoyVanBeek** [comment]
It depends on the ordering of startup I think, so timing and that can fail. We should add the networking service to the dependencies of the chrony service and not rely on timing but explicit ordering.

**Comment by MatthijsBurgh** [comment]
Netwerk-online,but that would probably airtight.

**Comment by PetervDooren** [comment]
I've tested this and it is indeed still a problem on hero2

**Comment by MatthijsBurgh** [comment]
Indeed, I also experienced it. The problem is caused by the network not being online automatically.
