### ISSUE TITLE
Print Toyota tray attachment

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#730]

**Comment by MatthijsBurgh** [comment]
See 
https://qa.hsr.io/en/question/1161/a-tray-that-is-held-by-the-hsr-using-the-dspl-restaurant-task/

**Comment by MatthijsBurgh** [comment]
@SamAlexandrov could you do this?

**Comment by MatthijsBurgh** [comment]
I already have somebody who can print these. @hvrooy, @LoyVanBeek @jlunenburg @JosjaG @LarsJanssenTUe @PetervDooren  Shall I print two of them?

**Comment by LarsJanssenTUe** [comment]
Is it a problem to do it one by one? Because that is what I would do, so the design can be improved if necessary.

**Comment by MatthijsBurgh** [comment]
We can do one by one, but I would like to take more than one to the German Open.

**Comment by hvrooy** [comment]
I will have 'the University' print one item, and ask for a step file from the designer, so we may be able to change the tray interface for a tray of ours.

**Comment by hvrooy** [comment]
Item has been printed, so it can be attached to the robot and tested. There is more than one way for HERO to hold the thing, though....
