### ISSUE TITLE
Hero does not rise in simulator

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue_robocup#753]
In the simulator. Hero's head does not rise with his arm like it does in reality. This causes problems since the robots belief of its configuration does not match its configuration in simulation.

For example when segmenting objects on the dinner table the camera image is taken from a lower position than the robot beliefs. Therefore an object is detected which is the size of the entire dinner table.

**Comment by LoyVanBeek** [comment]
That's weird. 
Who commands this rise IRL and why doesn't it happen in simulation?

**Comment by MatthijsBurgh** [comment]
fixed by: https://github.com/tue-robotics/hero_bringup/commit/2aca8a9bc60a8df12c2302af5d7cd57ea3ca9d00
