### ISSUE TITLE
Hacks in get_arm API

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#767]
Introduced in cf87033ffe81b378eb1def10acafc3d952f86ffc

The whole arms stuff require some serious thoughts about the design.

**Comment by alberth** [comment]
You want the challenge to work => you need to verify beforehand that the robot can do everything you want => you need a decision procedure for that.

Specifying in a challenge what you expect from an arm implements the latter for an arm.

So what is wrong with it?
