### ISSUE TITLE
Asus Xtion

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#780]

**Comment by hvrooy** [comment]
The ASUS camera in the lab seems to be depth only, so not sufficient.
I found a useful one for USD 300 (ex customs and transportation) in China.
Takes 5 days to be delivered via DHL.
See http://xtionprolive.com/asus-xtion-pro-live

**Comment by LarsJanssenTUe** [comment]
> The ASUS camera in the lab seems to be depth only, so not sufficient.
> I found a useful one for USD 300 (ex customs and transportation) in China.
> Takes 5 days to be delivered via DHL.
> See http://xtionprolive.com/asus-xtion-pro-live

Before this is ordered it might be worthwhile to wait for the response @jlunenburg get from smart robotics? On the other side if we need one it is not really handy/nice to use somebody else's hardware.

**Comment by LarsJanssenTUe** [comment]
Conclusion @hvrooy is gonna order one.

**Comment by MatthijsBurgh** [comment]
Camera has arrived.
