### ISSUE TITLE
Blocking speech

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#782]
Currently there is no option to give an argument that makes the speech blocking. Additionally to this a closer look could be taken into the talking speed of Hero (should be a parameter in the bringup)

**Comment by MatthijsBurgh** [comment]
I have checked the speech bridge. It works correctly. It waits if blocking is true, and return immediately, if false.

**Comment by LoyVanBeek** [comment]
Is the parameter correctly passed on?

**Comment by LoyVanBeek** [comment]
In ['where-is-this'](https://github.com/tue-robotics/tue_robocup/blob/rgo2019/challenge_where_is_this/src/challenge_where_is_this/inform_machine.py) all `Say`-states have `block=True`. 
Say [calls](https://github.com/tue-robotics/tue_robocup/blob/master/robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py#L73) robot.speech.speak
This then puts the [`block`-param in the request](https://github.com/tue-robotics/tue_robocup/blob/master/robot_skills/src/robot_skills/speech.py#L78), which has so far always worked.

So something's fishy...

**Comment by MatthijsBurgh** [comment]
> In ['where-is-this'](https://github.com/tue-robotics/tue_robocup/blob/rgo2019/challenge_where_is_this/src/challenge_where_is_this/inform_machine.py) all `Say`-states have `block=True`.
> Say [calls](https://github.com/tue-robotics/tue_robocup/blob/master/robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py#L73) robot.speech.speak
> This then puts the [`block`-param in the request](https://github.com/tue-robotics/tue_robocup/blob/master/robot_skills/src/robot_skills/speech.py#L78), which has so far always worked.
> 
> So something's fishy...

Has always worked... HERO uses bridge nodes...

But the bridge node can't handle multiple talking requests. Older ones are overruled by newer ones. @DvanDinther is looking into this to fix it. (Still this shouldn't happen if the SM uses blocking=True. Then the SM should call the service, while it is still speaking.)

**Comment by LoyVanBeek** [comment]
So the bridge node should wait for active speech to finish before starting a new one. 
This can be done by checking if there is an active goal and then `wait_for_result` before continuing with the current.
