### ISSUE TITLE
Fix challenge-robust

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#785]

**Comment by jlunenburg** [comment]
Indeed, I 'looked' at it without having access to a working robot or simulator. How can we reproduce this problem?

**Comment by MatthijsBurgh** [comment]
The problem is that the robot doesn't drive after using startChallengeRobust without using the door. If you use a navigateTo state, It gets a plan, it goes to execute plan, but the robot doesn't drive.

It didn't show in the simulator, correct?

**Comment by LoyVanBeek** [comment]
At German Open, @PetervDooren fixed this by introducing a little sleep somewhere. My money is on something not initialized. @PetervDooren can you elaborate of where the sleep is?

**Comment by PetervDooren** [comment]
The problem is that during the german open, many challenges start inside the arena. Therefore startChallengeRobust is not required. What many people did instead was use the states utility.Initialise() followed by utility.SetInitialPose() followed by the rest of their challenge.
The problem appears to be that if the first state of their challenge involves driving (which is most of the time) the robot would not drive.
Adding a sleep after the utility.Initialise() state fixed the problem. It might be that the Initialise state is exited before the local planner is actually initialised. But this is just speculation on my part.

**Comment by LarsJanssenTUe** [comment]
Tests schedule should show whether it is definitely broken and possibly where.

**Comment by LarsJanssenTUe** [comment]
The terminal output of hero-challenge-serving-drinks. Here the robot did not start driving.

[INFO][/state_machine][1558192600.346127]: State machine starting in initial state 'INITIALIZE' with userdata: 
	[]
[INFO][/state_machine][1558192600.450116]: TF link between /map and /base_link is checked. If it takes longer than a second, probably an error. Do a restart!!!
[INFO][/state_machine][1558192600.550710]: State machine transitioning 'INITIALIZE':'initialized'-->'WAIT_1'
[INFO][/state_machine][1558192600.651134]: State machine transitioning 'WAIT_1':'waited'-->'SET_INITIAL_POSE'
[INFO][/state_machine][1558192600.679294]: Set initial pose to 2.5, -0.5, 0.0
[INFO][/state_machine][1558192601.680876]: State machine transitioning 'SET_INITIAL_POSE':'done'-->'INSPECT_BAR'
[INFO][/state_machine][1558192601.681203]: State machine starting in initial state 'NAVIGATE_TO_INSPECT' with userdata: 
	[]
[INFO][/state_machine][1558192601.681419]: State machine starting in initial state 'START_ANALYSIS' with userdata: 
	[]
[INFO][/state_machine][1558192601.781913]: State machine transitioning 'START_ANALYSIS':'done'-->'NAVIGATE'
[INFO][/state_machine][1558192601.782191]: State machine starting in initial state 'GET_PLAN' with userdata: 
	[]
[INFO][/state_machine][1558192601.905613]: choosing best entity from this list (name->weight):
	[('bar_table', 0)]
[ INFO][/hero/local_planner][1558192601.932880630]: Trajectory Generator configured:
    - Samples [x,y,th] : [4,10,10]
    - Simulation time : 2.5 [seconds]
    - Simulation period : 0.1 [seconds]
    - Use DWA : 1 [-]
    - Granularity : 0.1 [m]
    - Angular granularity : 0.1 [rad]

[ INFO][/hero/local_planner][1558192601.932918291]: Switches configured:
    - Yaw error : 1.6 [rad]
    - Goal distance : 0.3 [m]
    - Plan distance : 0.5 [m]

[ INFO][/hero/local_planner][1558192601.932956987]: Scales configured:
    - Align:
        - align scale : 1 [-]
        - plan scale : 1 [-]
        - goal scale : 0 [-]
        - obstacle scale : 0.1 [-]
    - Default:
        - align scale : 1 [-]
        - plan scale : 0 [-]
        - goal scale : 1 [-]
        - obstacle scale : 0.03 [-]
    - Arrive:
        - align scale : 1 [-]
        - plan scale : 0 [-]
        - goal scale : 1 [-]
        - obstacle scale : 0.01 [-]

[INFO][/state_machine][1558192602.023125]: choosing best entity from this list (name->weight):
	[('bar_table', 0)]
[ INFO][/hero/global_planner][1558192602.069119528]: Position constraint has been changed, updating positions in constraint frame.
[ INFO][/hero/global_planner][1558192602.115730129]: Calculating map constraint area ...
[ INFO][/hero/global_planner][1558192602.117876588]: A* planner succesfully generated plan :)
[INFO][/state_machine][1558192602.119840]: 'I'm coming!'
[INFO][/state_machine][1558192602.169837]: State machine transitioning 'GET_PLAN':'goal_ok'-->'EXECUTE_PLAN'
[ INFO][/hero/local_planner][1558192603.632308716]: Local planner of type: 'dwa_local_planner/DWAPlannerROS' initialized.
[ INFO][/hero/local_planner][1558192608.656065989]: LPI: Started local planner thread @ 10 hz!

The terminal output of hero-challenge-serving-drinks with a hotfix which puts a wait between initialise and init_pose. Here the robot did start driving.

[INFO][/state_machine][1558192929.416721]: State machine transitioning 'INITIALIZE':'initialized'-->'WAIT_1'
[ INFO][/hero/local_planner][1558192931.438524139]: Trajectory Generator configured:
    - Samples [x,y,th] : [4,10,10]
    - Simulation time : 2.5 [seconds]
    - Simulation period : 0.1 [seconds]
    - Use DWA : 1 [-]
    - Granularity : 0.1 [m]
    - Angular granularity : 0.1 [rad]

[ INFO][/hero/local_planner][1558192931.438559299]: Switches configured:
    - Yaw error : 1.6 [rad]
    - Goal distance : 0.3 [m]
    - Plan distance : 0.5 [m]

[ INFO][/hero/local_planner][1558192931.438583626]: Scales configured:
    - Align:
        - align scale : 1 [-]
        - plan scale : 1 [-]
        - goal scale : 0 [-]
        - obstacle scale : 0.1 [-]
    - Default:
        - align scale : 1 [-]
        - plan scale : 0 [-]
        - goal scale : 1 [-]
        - obstacle scale : 0.03 [-]
    - Arrive:
        - align scale : 1 [-]
        - plan scale : 0 [-]
        - goal scale : 1 [-]
        - obstacle scale : 0.01 [-]

[ INFO][/hero/local_planner][1558192933.124112307]: Local planner of type: 'dwa_local_planner/DWAPlannerROS' initialized.
[INFO][/state_machine][1558192934.524445]: State machine transitioning 'WAIT_1':'waited'-->'SET_INITIAL_POSE'
[INFO][/state_machine][1558192934.559804]: Set initial pose to 2.5, -0.5, 0.0
[INFO][/state_machine][1558192935.561251]: State machine transitioning 'SET_INITIAL_POSE':'done'-->'INSPECT_BAR'
[INFO][/state_machine][1558192935.561557]: State machine starting in initial state 'NAVIGATE_TO_INSPECT' with userdata: 
	[]
[INFO][/state_machine][1558192935.561807]: State machine starting in initial state 'START_ANALYSIS' with userdata: 
	[]
[INFO][/state_machine][1558192935.662374]: State machine transitioning 'START_ANALYSIS':'done'-->'NAVIGATE'
[INFO][/state_machine][1558192935.662646]: State machine starting in initial state 'GET_PLAN' with userdata: 
	[]
[INFO][/state_machine][1558192935.796708]: choosing best entity from this list (name->weight):
	[('bar_table', 0)]
[INFO][/state_machine][1558192935.912010]: choosing best entity from this list (name->weight):
	[('bar_table', 0)]
[ INFO][/hero/global_planner][1558192935.941048499]: Position constraint has been changed, updating positions in constraint frame.
[ INFO][/hero/global_planner][1558192935.987863251]: Calculating map constraint area ...
[ INFO][/hero/global_planner][1558192935.990431752]: A* planner succesfully generated plan :)
[INFO][/state_machine][1558192935.992302]: 'I'm on my way!'
[ INFO][/hero/local_planner][1558192936.002120635]: Incoming actionlib plan.
[INFO][/state_machine][1558192936.051969]: State machine transitioning 'GET_PLAN':'goal_ok'-->'EXECUTE_PLAN'
[ INFO][/hero/local_planner][1558192938.147418166]: LPI: Started local planner thread @ 10 hz!
[ INFO][/hero/local_planner][1558192938.155069346]: State = Default

- @PetervDooren

**Comment by LarsJanssenTUe** [comment]
Also, starting a challenge using the launch file, like `hero-challenge-find-my-mates`, this problem will occur. However if that challenge is started by launching `hero-free-mode` followed by `rosrun challenge_find_my_mates find_my_mates.py hero`. The challenge will start without problems.

**Comment by LarsJanssenTUe** [comment]
Any idea what might be causing this @jlunenburg and @LoyVanBeek ?

**Comment by MatthijsBurgh** [comment]
> Also, starting a challenge using the launch file, like `hero-challenge-find-my-mates`, this problem will occur. However if that challenge is started by launching `hero-free-mode` followed by `rosrun challenge_find_my_mates find_my_mates.py hero`. The challenge will start without problems.
> 
> * @PetervDooren

This shouldn't make any difference. So this is more evidence for something not being initialized yet.

**Comment by LoyVanBeek** [comment]
> This shouldn't make any difference. So this is more evidence for something not being initialized yet.

I agree and I think we all agree that our main hypothesis is a timing problem/race-condition. Problem is finding out between what. 

One approach could be is to monitor all topics on the chain between the challenge and `/cmd_vel` and see where it stops?

**Comment by MatthijsBurgh** [comment]
Could be the first analysis.

**Comment by LarsJanssenTUe** [comment]
@MatthijsBurgh en @PetervDooren can you pick this up again?

**Comment by MatthijsBurgh** [comment]
I could check the chain as suggested by @LoyVanBeek. I also propose to build in a hacky solution. I will check the average time of the states for waiting for the door, driving etc. I will then build in a sleep state, which waits that long.

**Comment by MatthijsBurgh** [comment]
The hack could be replaced by waiting for the footprint of the local planner. I experienced that the robot starts driving after the footprint is published.
