### ISSUE TITLE
Tray for Restaurant challenge

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#789]

**Comment by PetervDooren** [comment]
Currently the robot can grip the tray, however it cannot keep the tray upright. A different grip is required to use the tray properly.

**Comment by LarsJanssenTUe** [comment]
> Currently the robot can grip the tray, however it cannot keep the tray upright. A different grip is required to use the tray properly.

Is a different grip necessary or a different tray? Or both? @hvrooy what do you think?

**Comment by hvrooy** [comment]
A lighter/smaller tray may be good. We can also adjust the gripper force and/or redesign the shape of the tray-interface to make it shape-closed instead of force-closed. However this requires a more precice gripping. All options apply here.... WIP

**Comment by LoyVanBeek** [comment]
Would it make sense to have the tray handle in the middle of the tray instead of just on the side? Would reduce the torque needed. 
We should be careful with arm movements though, then.

**Comment by MatthijsBurgh** [comment]
An other option is to single item handover. But that would maybe really slow down the challenge.

**Comment by hvrooy** [comment]
I made a smaller, lighter tray. It is a basket shaped form (about 30x20x10 cm) to which i attached the handle, The handle is not quit aligned with the Z-axis. (at about 15 deg from it). Can be adjusted if needed. 
See if this works first....

**Comment by LarsJanssenTUe** [comment]
@JosjaG tested it and it seems to work quite nicely! Credits to @hvrooy!
