### ISSUE TITLE
Simulator computation power/speed

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#795]
Currently the simulator takes up an enormous chunk of the available computation power on the athome pc's. This need for computation power can result in unstable behavior and very low speeds.

**Comment by jlunenburg** [comment]
* See http://gazebosim.org/tutorials?tut=plugins_model&cat=write_plugin on how to write plugins

**Comment by jlunenburg** [comment]
Looking into what takes up the CPU to know what we need to improve:
* The 'launch HSR' section of hero_bringup/launch/simulation/simulation.launch causes the CPU load to increase from +/- 40% to +/- 115%

**Comment by MatthijsBurgh** [comment]
Due to changes by Toyota, some remaps needed to be updated. HERO is already driving much faster. I also experienced (N=1, N=2) that reducing the fake mass of the base in the URDF speeds up the sim as well.

**Comment by jlunenburg** [comment]
Ways to improve:
* Keep on hacking. Will probably not result in a fast and stable simulator
* Replacing a number of gazebo plugins and disabling the ones that are not needed. As @reinzor discussed with @LarsJanssenTUe he would like to work on this
* Adding hero to the fast simulator. This is an (undesired) backup but could work

For the latter two items, a proper description of the required interfaces is necessary. @MatthijsBurgh @PetervDooren @JosjaG who has a good overview of this?

**Comment by MatthijsBurgh** [comment]
The simulator was used on RWC2019 without performance issues.
