### ISSUE TITLE
[basic_functionalities] is task 2 (navigation) according to the rule book?

### ISSUE THREAD

**Issue by svddries** [tue-robotics/tue_robocup#8]
Now, we simply give some simple goals. Is this sufficient?

**Comment by rokusottervanger** [comment]
The idea is that the path is blocked during navigation to those simple goals. A door may be closed, a person may stand in the way or an object may be blocking the way. Clearing the way (moving the object, asking a person to move, opening the door) will give points as well as replanning. Right @LoyVanBeek ?

**Comment by LoyVanBeek** [comment]
This indeed will also yield points. Please see https://github.com/RoboCupAtHome/RuleBook/blob/master/Navigation.tex#L72
