### ISSUE TITLE
Challenge person recognition: In simulation, no response to call to learn face

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/tue_robocup#82]
When running the challenge in simulation, the executive asks for the backend to learn the face and waits for a response, but no response is returned. At the time of the call, amiddle prints this: *** Error in `/home/rokus/ros/indigo/system/devel/lib/ed/ed': corrupted double-linked list: 0x00007f9a9cf62560 ***

**Comment by reinzor** [comment]
Fixed during reo2016
