### ISSUE TITLE
image subscribers

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#846]
We don't want to store each new incoming message. Only when we are going to use it. Because we are now also subscribing to depth images. This should be improved, see 
https://answers.ros.org/question/269855/how-to-set-callback-queue-size-in-rospy/

Probably @MatthijsBurgh, @LoyVanBeek or @ar13pit should fix this. I am not assigning anyone, because the person actually doing this, should be assigned.

**Comment by LoyVanBeek** [comment]
Fair point, but the reason for subscribing directly is that then you don't have to wait as long to get a message, you can always get the latest from before you did your call to get images.

**Comment by MatthijsBurgh** [comment]
We should check the delay, between subscribing and unsubscribing and the proposed solution
