### ISSUE TITLE
Designators do not resolve to the same entity

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue_robocup#865]
In many challenges and robot smach states we assume that a designator will always resolve to the same entity. However there's no mechanism that ensures that this is the case. 

@jlunenburg suggested that we either assert that is a locking designator and lock it (not so convenient for the user) or use userdata to this end (easier for the end-user, less reusable).

This is an issue for after Sydney.

**Comment by MatthijsBurgh** [comment]
Lock that shit

**Comment by LoyVanBeek** [comment]
There's a bunch of states for locking and unlocking a designator. 
It's not convenient indeed. 

What could be handy is some syntax like this:
```python
with locked(some_designator) as locked:
    smach.StateMachine.add("FOO" , 
                           Bar(robot, locked), 
                           transitions={...})
```
