### ISSUE TITLE
ED Plugins in one master repo

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue_robocup#877]
We have a lot of ED plugins and all have separate repos. This is painful in terms of maintenance and locating plugins.

We can have a master repo called ed_plugins with a meta package and all the plugins as sub dirs/packages of this master repo.

I think @reinzor agrees with me on this.

**Comment by MatthijsBurgh** [comment]
I don't agree (yet). So please add extra arguments

**Comment by LarsJanssenTUe** [comment]
@ar13pit ping! Close or continue discussion please

**Comment by ar13pit** [comment]
@MatthijsBurgh I'm still for putting all the plugins in one repo as a multiple packages. It will be better maintained.

**Comment by MatthijsBurgh** [comment]
I am still not convinced...

**Comment by MatthijsBurgh** [comment]
Yes, it is closed 🥳

**Comment by ar13pit** [comment]
Haha well neither of us agreed upon anything. So best to leave ED as it is till it lives :)
