### ISSUE TITLE
RWC2019 aftermath

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#885]
- [x] action_server, PR merged https://github.com/tue-robotics/action_server/pull/116
- [x] amigo_bringup, PR merged https://github.com/tue-robotics/amigo_bringup/pull/108
- [x] amigo_description
- [x] amigo_hardware
- [x] amigo_moveit_config
- [x] amigo_msgs
- [x] amigo_ref_interpolator
- [x] ar_marker_detector
- [x] battery_manager
- [x] cb_base_navigation
- [x] cb_planner_msgs_srvs
- [x] code_profiler
- [x] control_msgs
- [x] conversation_engine
- [x] dashboard
- [x] dialogflow_ros
- [x] dragonfly_speech_recognition
- [x] dynamixel_jointstate_conversion
- [x] dynamixel_motor
- [x] dynamixel_ros_control
- [x] ed, PR merged https://github.com/tue-robotics/ed/pull/90
- [x] ed_gui_server
- [x] ed_localization
- [x] ed_moveit
- [x] ed_msgs
- [x] ed_navigation, PR merged https://github.com/tue-robotics/ed_navigation/pull/16
- [x] ed_object_models, PR merged  https://github.com/tue-robotics/ed_object_models/pull/59
- [x] ed_people_recognition, PR merged https://github.com/tue-robotics/ed_people_recognition/pull/4
- [x] ed_perception
- [x] ed_perception_models
- [x] ed_robocup, PR merged https://github.com/tue-robotics/ed_robocup/pull/12
- [x] ed_rviz_plugins
- [x] ed_sensor_integration, PR merged https://github.com/tue-robotics/ed_sensor_integration/pull/25
- [x] ed_tutorials
- [x] ed_wire
- [x] emc-env
- [x] emc_simulator
- [x] emc_system
- [x] emergency_speakup
- [x] ethercat_interface
- [x] fast_simulator
- [x] fast_simulator_data
- [x] geolib2
- [x] GPSRCmdGen
- [x] gitim
- [x] grammar_parser
- [x] gripper_detector
- [x] head_ref
- [x] head_ref_ed_client
- [x] hero-dashboard
- [x] hero-display
- [x] hero_bridge, PR merged https://github.com/tue-robotics/hero_bridge/pull/10
- [x] hero_bringup, PR merged https://github.com/tue-robotics/hero_bringup/pull/32
- [x] hero_description PR merged https://github.com/tue-robotics/hero_description/pull/6
- [x] hmi, PR merged https://github.com/tue-robotics/hmi/pull/18
- [x] hmi_telegram
- [x] image_recognition
- [x] image_recognition-release
- [x] image_recognition_wire
- [x] kaldi
- [x] kaldi_srilm
- [x] kinect_driver
- [x] matrix_creator_ros
- [x] multirobot_communication
- [x] navigation, PR merged https://github.com/tue-robotics/navigation/pull/11
- [x] nl_robot_console
- [x] node_alive
- [x] people_recognition, PR open https://github.com/tue-robotics/people_recognition/pull/20
- [x] pico_base_controller
- [x] pico_bringup
- [x] pico_talk
- [x] qr_detector_zbar
- [x] r5cop_demo
- [x] rgb_lights_manager
- [x] rgbd, PR mergedtue-robotics/rgbd#19
- [x] rgbd_msgs
- [x] robot-api
- [x] robot_launch_files, PR merged https://github.com/tue-robotics/robot_launch_files/pull/51
- [x] rtt
- [x] rtt_control_components
- [x] rtt_soem
- [x] rtt_tue_msgs
- [x] scl_filters
- [x] sergio_bringup
- [x] sergio_control
- [x] sergio_description
- [x] sergio_gripper_moveit_config
- [x] sergio_hardware
- [x] sergio_moveit_config
- [x] sergio_torso_calibration
- [x] simulink_models
- [x] slack_ros
- [x] snowboy_ros
- [x] soem
- [x] speech_recognition
- [x] telegram_ros, PR merged https://github.com/tue-robotics/telegram_ros/pull/13
- [x] teleop_twist_web
- [x] text_to_speech, PR merged https://github.com/tue-robotics/text_to_speech/pull/14
- [x] tf_server
- [x] tue-env, PR merged https://github.com/tue-robotics/tue-env/pull/413
- [x] tue-env-targets, PR merged https://github.com/tue-robotics/tue-env-targets/pull/80
- [x] tue-robotics.github.io
- [x] tue_config
- [x] tue_docs
- [x] tue_ethercat_drivers
- [x] tue_filesystem
- [x] tue_manipulation
- [x] tue_manipulation_msgs
- [x] tue_mobile_ui
- [x] tue_msgs
- [x] tue_robocup
- [x] tue_serialization
- [x] tue_simulink_ethercat
- [x] tue_teleop_keyboard
- [x] upower_ros
- [x] virtual_cam
- [x] wire

tue_robocup:
  - [x] challenge_cleanup
  - [x] challenge_demo, no changes
  - [x] challenge_dishwasher, no changes
  - [x] challenge_eegpsr, no changes
  - [x] challenge_final
  - [x] challenge_find_my_mates
  - [x] challenge_following_and_guiding, no changes
  - [x] challenge_gpsr, no changes
  - [x] challenge_hand_me_that
  - [x] challenge_help_me_carry, no changes
  - [x] challenge_manipulation, no changes
  - [x] challenge_navigation, no changes
  - [x] challenge_person_recognition, no changes
  - [x] challenge_presentation
  - [x] challenge_receptionist
  - [x] challenge_restaurant
  - [x] challenge_rips
  - [x] challenge_serving_drinks
  - [x] challenge_set_a_table, no changes
  - [x] challenge_set_the_table
  - [x] challenge_speech_recognition, no changes
  - [x] challenge_spr, only empty knowledge file
  - [x] challenge_storing_groceries, no changes
  - [x] challenge_take_out_the_garbage
  - [x] challenge_test, no changes
  - [x] challenge_where_is_this
  - [x] ~robocup_knowledge~, include in challenge branches
  - [x] robot_skills
  - [x] robot_smach_states
  - [x] test_tools, no changes

examples for robot_smach_states:
- [x] Give_directions
- [x] Designator_iterator
- [x] human_interaction
     - [x] say 
     - [x] AskYesNo
     - [x] WaitForPersonInFront
- [x] Show_image
- [x] Manipulation
     - [x] HandOverFromHuman
     - [x] HandOverToHuman
     - [x] CloseGripperOnHandOverToRobot
     - [x] SetGripper
- [x] Guidance
     - [x] TourGuide
- [x] Navigation
     - [x] ForceDrive 
- [x] String_Manipulation (docstrings in place)
- [x] Utility
     - [x] AttrDesignator (docstrings in place)
     - [x] ValueByKeyDesignator (docstrings in place)
- [x] World_model
     - [x] SegmentObjects

**Comment by LoyVanBeek** [comment]
For tue_robocup, I propose to split the PR into: 

- robot_smach_states+robot_skills, who'll get a thorough review
- separate PR for each challenge, which can be less thoroughly reviewed.

**Comment by LoyVanBeek** [comment]
Checked above means PR merged or none needed?

**Comment by MatthijsBurgh** [comment]
Both, Checked means no action needed anymore. I deleted all the unchanged rwc2019 branches already. And now we will start merging stuff, those will need to be checked, when a PR is merged.
