### ISSUE TITLE
Standardize python docstrings

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#898]
Many style of docstring are used. This should be consistent. As automatically generated documentation is also an issue, #884. The docstring should be compatibel with the documentation generator we will be using. Preferably one which has automatic linking

**Comment by Rayman** [comment]
This package seems really nice: https://github.com/mikepurvis/catkin_tools_document. Builds documentation of the whole workspace with rosdoc_lite.

**Comment by LoyVanBeek** [comment]
Another very useful thing: add type hints! If you use PyCharm, that'll also help with completion

**Comment by LarsJanssenTUe** [comment]
@MatthijsBurgh I think this issue can now be closed? Although a new one might be opened were we keep tabs on which repo's still need documentation?

**Comment by MatthijsBurgh** [comment]
It might be good to have some examples, so people will use the good styling.
