### ISSUE TITLE
Compose arm of seperate arm_parts

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#911]
Currently the force_sensing_arm is a class that inherits from the class arm. This works for now, but if more sensors, such as for example the camera are added to the arm this will get messy. Therefore it is preferred to compose an arm of separate parts just as the robot is.

**Comment by LarsJanssenTUe** [comment]
Currently there is only a check on whether a force_sensor is required

**Comment by PetervDooren** [comment]
Currently working on this in #1058
