### ISSUE TITLE
Sanity check of robot smach states

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#912]
It's desirable to check for available (robot) parts and methods within parts on construction of the statemachine. This might catch many bugs before they happen in practice (already during programming, simulating). 

A suggestion is to use [AST](https://docs.python.org/3/library/ast.html) to parse the execute method and inspect which robot parts and attributes of these parts are required.

Some questions:
* Do or don't we want to fork smach?
* How can we enforce the use of a parameter check. Adding it to the `__init__` is not convenient: that would mean that `super` needs to be called at the *end* of the `__init__` of the deriving class. Using a separate method is hard to enforce. The following snipped might provide some inspiration:
```python
class smach.State(...):
    def __init__(...):
        self._is_checked = False

    def check_attributes(self):
        ....
        self._is_checked = True

    @property
    def is_checked(self):
        return self._is_checked


class smach.StateMachine(...):
    def add(self, state):
        assert(state.is_checked, "Attributes of {} have not been checked, did you call 'check_attributes'?")
```

**Comment by MatthijsBurgh** [comment]
Needs way more development. Not possible right now. So unassigning myself.
