### ISSUE TITLE
Find people finds people outside the assigned area

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#939]

**Comment by PetervDooren** [comment]
Is there anymore info on this issue. How do we reproduce this issue

**Comment by MatthijsBurgh** [comment]
https://github.com/tue-robotics/tue_robocup/blob/22e6874f403c21814005ce4808ed722755d8edc9/robot_smach_states/src/robot_smach_states/human_interaction/find_people_in_room.py#L187-L198

Is this the issue?

**Comment by LarsJanssenTUe** [comment]
> Is there anymore info on this issue. How do we reproduce this issue

See the video of the finals in Sydney. No people outside of the arena should be detected (I know that there was even some kind of buffer zone inside the arena in which no people should be detected), but they were.

**Comment by MatthijsBurgh** [comment]
Yes I know, but it the suggested code the origin of the problem.
