### ISSUE TITLE
Waiting for the "ping" takes way to long in the demo

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#942]
The grammar that is loaded in the demo is unnecessarily big. Most of these things are never used/we can not even do. Cleaning this up would help a lot

**Comment by LarsJanssenTUe** [comment]
Another proposal is to cache the grammar somehow somewhere

**Comment by DvanDinther** [comment]
Could not replicate the issue. A change to the demo grammar might have solved the issue, although this change was very minor.
