### ISSUE TITLE
Prevent fitting an object such that it collides with the environment and reject big fitting jumps 

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/tue_robocup#972]

**Comment by MatthijsBurgh** [comment]
Please add description as title isn't clear to me.

**Comment by PetervDooren** [comment]
sub project goals
- [ ] update ed SimpleQuery and Query
- [ ] create intersect for radius
- [ ] process intersect comments
- [ ] create collision check between two shapes

**Comment by LarsJanssenTUe** [comment]
@PetervDooren I know this is not solved, but a start has been made with that merge. Would you like to keep this open? Otherwise please close it ;)

**Comment by PetervDooren** [comment]
PR https://github.com/tue-robotics/ed_sensor_integration/pull/31 solves one case where this happens. However we do not know for sure if this has completely solved the problem. I suggest we keep a lookout for this issue in the future
