### ISSUE TITLE
Fix docstrings syntax for documentation 

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#988]
### cross-references
https://stackoverflow.com/questions/7753805/sphinx-automodule-how-to-reference-classes-in-same-module and https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-syntax

Use 
```
:class:'.A'
``` 

but with backticks instead of quotes

_Originally posted by @LoyVanBeek in https://github.com/tue-robotics/tue_robocup/pull/978_

**Comment by LoyVanBeek** [comment]
For the documantation generator, it's also important to have a newline between the docstring summary and the first `:param` stuff. So 

```
This method does methody-things

:param thing: A thing to method on`
``` is OK

but 

```
This method does methody-things
:param thing: A thing to method on`
``` is not ok.

**Comment by LarsJanssenTUe** [comment]
@MatthijsBurgh I think this can be closed?

**Comment by MatthijsBurgh** [comment]
Same here, we should come up with an example for correct docstring styling.
