### ISSUE TITLE
ED construction is slow

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#998]
If RGBD shared memory server is not running, the clients will try for 5 seconds. With multiple clients, this is a pain in the *ss.

Related to https://github.com/tue-robotics/rgbd/issues/15

**Comment by LoyVanBeek** [comment]
They'll what? 

>  the clients will *lry* for 5 seconds

**Comment by MatthijsBurgh** [comment]
Is going to be fixed in tue-robotics/rgbd#23
